version: "2"
run:
  timeout: 3m
linters:
  default: none
  enable:
    - errcheck
    - exhaustive
    - gocritic
    - gosec
    - govet
    - ineffassign
    - misspell
    - staticcheck
    - unused
formatters:
  enable:
    - gofmt
