package tui

import (
	"strings"
	"testing"

	tea "charm.land/bubbletea/v2"

	"dolphin/internal/types"
)

// simModel holds the model and a chan-based message inbox, simulating
// what tea.Program does but without a TTY requirement.
type simModel struct {
	m     model
	inbox chan tea.Msg
}

func newSim(width, height int) *simModel {
	m := newModel()
	m.width = width
	m.height = height
	m.agentName = "Dolphin"
	m.modelName = "claude"
	m.showTools = true
	m.showThinking = true
	m.ready = true // skip WindowSizeMsg init
	m.textarea.SetWidth(width - 1)
	m.viewport.SetWidth(width)
	m.viewport.SetHeight(height - 5)
	return &simModel{m: m, inbox: make(chan tea.Msg, 100)}
}

func (s *simModel) send(msg tea.Msg) {
	s.inbox <- msg
}

func (s *simModel) step() {
	// Drain all pending messages, applying them sequentially.
	// Also execute any returned tea.Cmd to capture side-effect messages
	// (e.g. permResponseMsg generated by permission dialog keys).
	for {
		select {
		case msg := <-s.inbox:
			newM, cmd := s.m.Update(msg)
			s.m = newM.(model)
			if cmd != nil {
				cmdMsg := cmd()
				if cmdMsg != nil {
					newM2, _ := s.m.Update(cmdMsg)
					s.m = newM2.(model)
				}
			}
		default:
			return
		}
	}
}

func (s *simModel) stepAll() {
	for len(s.inbox) > 0 {
		s.step()
	}
}

func TestE2E_StreamingConversation(t *testing.T) {
	sim := newSim(100, 30)
	sim.m.msgChan = make(chan userInput, 1)
	sim.m.permCh = make(chan string, 1)

	// Round 1: model change + thinking + streaming content.
	sim.send(modelChangeMsg{name: "claude-sonnet"})
	sim.send(thinkingMsg{text: "Let me think about this..."})
	sim.stepAll()

	// Simulate streaming response in small chunks.
	chunks := []string{"Here", " is", " a **bold**", " response", " with", " `code`", " and", " multiple", " lines.\nNew line here."}
	for _, chunk := range chunks {
		sim.send(contentMsg{text: chunk})
	}
	sim.stepAll()

	// Verify streaming created messages.
	if len(sim.m.messages) == 0 {
		t.Error("expected messages after streaming")
	}
	if sim.m.textBlockDirty {
		// Flush finalizes the dirty block.
		sim.send(flushMsg{})
		sim.stepAll()
		if sim.m.textBlockDirty {
			t.Error("textBlockDirty should be false after flush")
		}
	}

	// Round 2: tool call + result.
	sim.send(toolCallMsg{call: types.ToolCall{Name: "read_file", Arguments: "path/to/file"}})
	sim.stepAll()
	sim.send(toolResultMsg{result: types.ToolResult{Content: "file contents here", IsError: false}})
	sim.stepAll()

	// Round 3: more streaming text after tool.
	sim.send(contentMsg{text: "Based on the file, I recommend..."})
	sim.stepAll()

	// User submits input.
	sim.send(userSubmitMsg{in: userInput{text: "What about a different approach?"}})
	sim.stepAll()

	// Round 4: error tool result.
	sim.send(toolResultMsg{result: types.ToolResult{Content: "permission denied", IsError: true}})
	sim.stepAll()

	// Verify the model has accumulated messages.
	if len(sim.m.messages) == 0 {
		t.Error("expected messages after conversation")
	}
	if sim.m.viewport.View() == "" {
		t.Error("expected viewport content after conversation")
	}

	// Verify dirty block is finalized at the end.
	if sim.m.textBlockDirty {
		t.Error("textBlockDirty should be false when conversation is done")
	}
}

func TestE2E_PermissionFlow(t *testing.T) {
	sim := newSim(80, 24)
	permCh := make(chan string, 1)

	// Trigger permission dialog, delivering the response channel via the
	// message (the real flow — the model must reply on THIS channel).
	sim.send(permRequestMsg{prompt: "Allow tool execution?", ch: permCh})
	sim.stepAll()

	if sim.m.permDialog == nil {
		t.Fatal("expected permission dialog to be active")
	}
	if sim.m.permCh != permCh {
		t.Fatal("model should hold the request's response channel")
	}

	// 'a' (always) needs double-press confirmation.
	sim.send(tea.KeyPressMsg{Code: 'a'})
	sim.stepAll()
	if sim.m.permDialog == nil {
		t.Error("permission dialog should still show after first 'a'")
	}
	sim.send(tea.KeyPressMsg{Code: 'a'})
	sim.stepAll()

	if sim.m.permDialog != nil {
		t.Error("permission dialog should be dismissed after second 'a'")
	}

	select {
	case choice := <-permCh:
		if choice != "always" {
			t.Errorf("expected 'always', got %q", choice)
		}
	default:
		t.Error("expected permission choice to be received")
	}
}

func TestE2E_MultiTurnMemory(t *testing.T) {
	sim := newSim(120, 30)

	// Simulate 5 rounds, each with many messages to stress trimFront.
	for round := 0; round < 5; round++ {
		sim.send(userSubmitMsg{in: userInput{text: "Question from round"}})
		sim.stepAll()

		// Streaming response: 100 chunks per round.
		for i := 0; i < 100; i++ {
			sim.send(contentMsg{text: "response chunk "})
		}
		sim.stepAll()

		// Tool call + result.
		sim.send(toolCallMsg{call: types.ToolCall{Name: "search", Arguments: "query"}})
		sim.stepAll()
		sim.send(toolResultMsg{result: types.ToolResult{Content: "result data"}})
		sim.stepAll()

		// More text after tool.
		sim.send(contentMsg{text: "Analysis after tool result."})
		sim.stepAll()
	}

	if len(sim.m.messages) == 0 {
		t.Error("expected messages after multi-turn")
	}
	if len(sim.m.messages) >= maxMessages {
		t.Errorf("messages should be trimmed under %d, got %d", maxMessages, len(sim.m.messages))
	}
	if sim.m.viewport.View() == "" {
		t.Error("empty viewport after multi-turn")
	}

	// Verify trim happened at least once.
	// 5 rounds * (1 user + ~100 text + 1 tool_call + 1 tool_result + 1 text) > 500
	if len(sim.m.messages) > maxMessages {
		t.Errorf("trimFront did not trim enough: %d > %d", len(sim.m.messages), maxMessages)
	}
}

func TestE2E_ToggleToolsAndThinking(t *testing.T) {
	sim := newSim(80, 24)
	sim.m.showTools = false
	sim.m.showThinking = false

	// Toggle tools on via /tools command.
	sim.m.textarea.SetValue("/tools")
	newM, _ := sim.m.Update(tea.KeyPressMsg{Code: tea.KeyEnter})
	sim.m = newM.(model)
	newM, cmd := sim.m.Update(tea.KeyPressMsg{Code: tea.KeyEnter})
	sim.m = newM.(model)
	if cmd != nil {
		cmd()
	}
	sim.stepAll()

	if !sim.m.showTools {
		t.Error("showTools should be true after /tools toggle")
	}

	// Send a tool call — should be visible.
	sim.send(toolCallMsg{call: types.ToolCall{Name: "test_tool", Arguments: "{}"}})
	sim.stepAll()

	// Toggle thinking on.
	sim.m.textarea.SetValue("/thinking")
	newM, _ = sim.m.Update(tea.KeyPressMsg{Code: tea.KeyEnter})
	sim.m = newM.(model)
	newM, cmd = sim.m.Update(tea.KeyPressMsg{Code: tea.KeyEnter})
	sim.m = newM.(model)
	if cmd != nil {
		cmd()
	}
	sim.stepAll()

	if !sim.m.showThinking {
		t.Error("showThinking should be true after /thinking toggle")
	}

	// Send thinking — should be visible.
	sim.send(thinkingMsg{text: "processing..."})
	sim.stepAll()

	content := sim.m.viewport.View()
	if !strings.Contains(content, "test_tool") {
		t.Error("viewport should contain tool call after toggle")
	}
	if !strings.Contains(content, "processing") {
		t.Error("viewport should contain thinking after toggle")
	}
}

func TestE2E_PermissionDialogDismissal(t *testing.T) {
	sim := newSim(80, 24)
	permCh := make(chan string, 1)

	// Trigger permission dialog with the response channel.
	sim.send(permRequestMsg{prompt: "Allow?", ch: permCh})
	sim.stepAll()

	if sim.m.permDialog == nil {
		t.Fatal("expected permission dialog to be active")
	}

	// Press 'n' to deny — modal closes and replies on the channel.
	sim.send(tea.KeyPressMsg{Code: 'n'})
	sim.stepAll()

	if sim.m.permDialog != nil {
		t.Error("permission dialog should be dismissed after 'n' key")
	}

	select {
	case choice := <-permCh:
		if choice != "deny" {
			t.Errorf("expected 'deny', got %q", choice)
		}
	default:
		t.Error("expected permission choice to be received")
	}
}

// The permission dialog is modal: pressing ordinary keys (e.g. letters that
// aren't y/a/n) must NOT type into the textarea while the dialog is open.
func TestE2E_PermissionDialogSwallowsOtherKeys(t *testing.T) {
	sim := newSim(80, 24)
	permCh := make(chan string, 1)
	sim.send(permRequestMsg{prompt: "Allow?", ch: permCh})
	sim.stepAll()

	// A random letter neither resolves the dialog nor reaches the textarea.
	sim.send(tea.KeyPressMsg{Code: 'x'})
	sim.stepAll()

	if sim.m.permDialog == nil {
		t.Error("dialog should still be open after unrelated key")
	}
	if sim.m.textarea.Value() != "" {
		t.Errorf("textarea should be empty (modal swallows keys), got %q", sim.m.textarea.Value())
	}

	// Arrow-key navigation moves the active choice without resolving.
	sim.send(tea.KeyPressMsg{Code: tea.KeyRight})
	sim.stepAll()
	if sim.m.permDialog == nil {
		t.Fatal("dialog should still be open after right arrow")
	}
	if sim.m.permDialog.active != 1 {
		t.Errorf("right arrow should move active to index 1, got %d", sim.m.permDialog.active)
	}

	// Enter confirms the highlighted choice (index 1 → always).
	sim.send(tea.KeyPressMsg{Code: tea.KeyEnter})
	sim.stepAll()
	if sim.m.permDialog != nil {
		t.Error("dialog should be dismissed after enter")
	}
	select {
	case choice := <-permCh:
		if choice != "always" {
			t.Errorf("expected 'always' from enter on index 1, got %q", choice)
		}
	default:
		t.Error("expected permission choice to be received")
	}
}

func TestE2E_DirtyBlockFinalizedByNonText(t *testing.T) {
	sim := newSim(100, 30)

	// Start streaming text.
	sim.send(contentMsg{text: "First chunk"})
	sim.stepAll()
	if sim.m.textBlockDirty {
		t.Error("first text entry should not set dirty")
	}

	// Streaming merge sets dirty.
	sim.send(contentMsg{text: " merged"})
	sim.stepAll()
	if !sim.m.textBlockDirty {
		t.Error("text merge should set dirty")
	}

	// Tool call should finalize the dirty block.
	sim.send(toolCallMsg{call: types.ToolCall{Name: "finalize_test", Arguments: "{}"}})
	sim.stepAll()
	if sim.m.textBlockDirty {
		t.Error("non-text entry should clear dirty flag")
	}
}

func TestE2E_DirtyBlockFinalizedByFlush(t *testing.T) {
	sim := newSim(100, 30)

	// Start streaming text.
	sim.send(contentMsg{text: "First chunk"})
	sim.stepAll()
	sim.send(contentMsg{text: " merged"})
	sim.stepAll()
	if !sim.m.textBlockDirty {
		t.Error("text merge should set dirty")
	}

	// Flush should finalize the dirty block.
	sim.send(flushMsg{})
	sim.stepAll()
	if sim.m.textBlockDirty {
		t.Error("flush should clear dirty flag")
	}
}
