// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package graph

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
	"time"
)

type Agent struct {
	ID           string      `json:"id"`
	Name         string      `json:"name"`
	Kind         AgentKind   `json:"kind"`
	Status       AgentStatus `json:"status"`
	ExternalID   string      `json:"externalID"`
	Capabilities []string    `json:"capabilities,omitempty"`
	LastSeenAt   *time.Time  `json:"lastSeenAt,omitempty"`
	CreatedAt    time.Time   `json:"createdAt"`
	UpdatedAt    time.Time   `json:"updatedAt"`
}

type Comment struct {
	ID          string             `json:"id"`
	IssueID     string             `json:"issueID"`
	AuthorID    string             `json:"authorID"`
	ParentID    *string            `json:"parentID,omitempty"`
	Body        string             `json:"body"`
	ContentType CommentContentType `json:"contentType"`
	CreatedAt   time.Time          `json:"createdAt"`
	UpdatedAt   time.Time          `json:"updatedAt"`
	Author      *Agent             `json:"author"`
}

type Issue struct {
	ID          string           `json:"id"`
	Number      int32            `json:"number"`
	ProjectID   string           `json:"projectID"`
	Title       string           `json:"title"`
	Description *string          `json:"description,omitempty"`
	State       IssueState       `json:"state"`
	Priority    Priority         `json:"priority"`
	CreatorID   string           `json:"creatorID"`
	ParentID    *string          `json:"parentID,omitempty"`
	DueDate     *time.Time       `json:"dueDate,omitempty"`
	ClosedAt    *time.Time       `json:"closedAt,omitempty"`
	CreatedAt   time.Time        `json:"createdAt"`
	UpdatedAt   time.Time        `json:"updatedAt"`
	Creator     *Agent           `json:"creator"`
	Assignees   []*IssueAssignee `json:"assignees,omitempty"`
	Labels      []*Label         `json:"labels,omitempty"`
}

type IssueAssignee struct {
	ID      string        `json:"id"`
	IssueID string        `json:"issueID"`
	AgentID string        `json:"agentID"`
	State   AssigneeState `json:"state"`
	Agent   *Agent        `json:"agent"`
}

type IssueConnection struct {
	Edges []*Issue `json:"edges"`
	Total int32    `json:"total"`
}

type Label struct {
	ID        string  `json:"id"`
	Name      string  `json:"name"`
	Color     *string `json:"color,omitempty"`
	ProjectID string  `json:"projectID"`
}

type LoginResult struct {
	Agent *Agent `json:"agent"`
	Token string `json:"token"`
}

type Mutation struct {
}

type Project struct {
	ID          string           `json:"id"`
	Name        string           `json:"name"`
	Description *string          `json:"description,omitempty"`
	CreatedAt   time.Time        `json:"createdAt"`
	UpdatedAt   time.Time        `json:"updatedAt"`
	Members     []*ProjectMember `json:"members,omitempty"`
}

type ProjectMember struct {
	ID        string      `json:"id"`
	ProjectID string      `json:"projectID"`
	AgentID   string      `json:"agentID"`
	Role      ProjectRole `json:"role"`
	Agent     *Agent      `json:"agent"`
}

type Query struct {
}

type TimelineEvent struct {
	ID        string    `json:"id"`
	IssueID   string    `json:"issueID"`
	ActorID   string    `json:"actorID"`
	EventType string    `json:"eventType"`
	CreatedAt time.Time `json:"createdAt"`
	Actor     *Agent    `json:"actor"`
}

type AgentKind string

const (
	AgentKindAi     AgentKind = "ai"
	AgentKindHuman  AgentKind = "human"
	AgentKindHybrid AgentKind = "hybrid"
)

var AllAgentKind = []AgentKind{
	AgentKindAi,
	AgentKindHuman,
	AgentKindHybrid,
}

func (e AgentKind) IsValid() bool {
	switch e {
	case AgentKindAi, AgentKindHuman, AgentKindHybrid:
		return true
	}
	return false
}

func (e AgentKind) String() string {
	return string(e)
}

func (e *AgentKind) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AgentKind(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AgentKind", str)
	}
	return nil
}

func (e AgentKind) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AgentKind) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AgentKind) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type AgentStatus string

const (
	AgentStatusOnline  AgentStatus = "online"
	AgentStatusBusy    AgentStatus = "busy"
	AgentStatusOffline AgentStatus = "offline"
	AgentStatusError   AgentStatus = "error"
)

var AllAgentStatus = []AgentStatus{
	AgentStatusOnline,
	AgentStatusBusy,
	AgentStatusOffline,
	AgentStatusError,
}

func (e AgentStatus) IsValid() bool {
	switch e {
	case AgentStatusOnline, AgentStatusBusy, AgentStatusOffline, AgentStatusError:
		return true
	}
	return false
}

func (e AgentStatus) String() string {
	return string(e)
}

func (e *AgentStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AgentStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AgentStatus", str)
	}
	return nil
}

func (e AgentStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AgentStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AgentStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type AssigneeState string

const (
	AssigneeStatePending   AssigneeState = "pending"
	AssigneeStateAccepted  AssigneeState = "accepted"
	AssigneeStateDeclined  AssigneeState = "declined"
	AssigneeStateCompleted AssigneeState = "completed"
)

var AllAssigneeState = []AssigneeState{
	AssigneeStatePending,
	AssigneeStateAccepted,
	AssigneeStateDeclined,
	AssigneeStateCompleted,
}

func (e AssigneeState) IsValid() bool {
	switch e {
	case AssigneeStatePending, AssigneeStateAccepted, AssigneeStateDeclined, AssigneeStateCompleted:
		return true
	}
	return false
}

func (e AssigneeState) String() string {
	return string(e)
}

func (e *AssigneeState) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AssigneeState(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AssigneeState", str)
	}
	return nil
}

func (e AssigneeState) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AssigneeState) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AssigneeState) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type CommentContentType string

const (
	CommentContentTypeMarkdown   CommentContentType = "markdown"
	CommentContentTypeToolCall   CommentContentType = "tool_call"
	CommentContentTypeToolResult CommentContentType = "tool_result"
	CommentContentTypeCodeDiff   CommentContentType = "code_diff"
	CommentContentTypeDecision   CommentContentType = "decision"
	CommentContentTypeApproval   CommentContentType = "approval"
	CommentContentTypeRejection  CommentContentType = "rejection"
	CommentContentTypeStructured CommentContentType = "structured"
)

var AllCommentContentType = []CommentContentType{
	CommentContentTypeMarkdown,
	CommentContentTypeToolCall,
	CommentContentTypeToolResult,
	CommentContentTypeCodeDiff,
	CommentContentTypeDecision,
	CommentContentTypeApproval,
	CommentContentTypeRejection,
	CommentContentTypeStructured,
}

func (e CommentContentType) IsValid() bool {
	switch e {
	case CommentContentTypeMarkdown, CommentContentTypeToolCall, CommentContentTypeToolResult, CommentContentTypeCodeDiff, CommentContentTypeDecision, CommentContentTypeApproval, CommentContentTypeRejection, CommentContentTypeStructured:
		return true
	}
	return false
}

func (e CommentContentType) String() string {
	return string(e)
}

func (e *CommentContentType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = CommentContentType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid CommentContentType", str)
	}
	return nil
}

func (e CommentContentType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *CommentContentType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e CommentContentType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type IssueState string

const (
	IssueStateOpen             IssueState = "open"
	IssueStateInProgress       IssueState = "in_progress"
	IssueStateBlocked          IssueState = "blocked"
	IssueStateReview           IssueState = "review"
	IssueStateClosedCompleted  IssueState = "closed_completed"
	IssueStateClosedNotPlanned IssueState = "closed_not_planned"
)

var AllIssueState = []IssueState{
	IssueStateOpen,
	IssueStateInProgress,
	IssueStateBlocked,
	IssueStateReview,
	IssueStateClosedCompleted,
	IssueStateClosedNotPlanned,
}

func (e IssueState) IsValid() bool {
	switch e {
	case IssueStateOpen, IssueStateInProgress, IssueStateBlocked, IssueStateReview, IssueStateClosedCompleted, IssueStateClosedNotPlanned:
		return true
	}
	return false
}

func (e IssueState) String() string {
	return string(e)
}

func (e *IssueState) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = IssueState(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid IssueState", str)
	}
	return nil
}

func (e IssueState) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *IssueState) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e IssueState) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type Priority string

const (
	PriorityCritical Priority = "critical"
	PriorityHigh     Priority = "high"
	PriorityMedium   Priority = "medium"
	PriorityLow      Priority = "low"
)

var AllPriority = []Priority{
	PriorityCritical,
	PriorityHigh,
	PriorityMedium,
	PriorityLow,
}

func (e Priority) IsValid() bool {
	switch e {
	case PriorityCritical, PriorityHigh, PriorityMedium, PriorityLow:
		return true
	}
	return false
}

func (e Priority) String() string {
	return string(e)
}

func (e *Priority) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = Priority(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid Priority", str)
	}
	return nil
}

func (e Priority) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *Priority) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e Priority) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ProjectRole string

const (
	ProjectRoleAdmin  ProjectRole = "admin"
	ProjectRoleMember ProjectRole = "member"
	ProjectRoleViewer ProjectRole = "viewer"
)

var AllProjectRole = []ProjectRole{
	ProjectRoleAdmin,
	ProjectRoleMember,
	ProjectRoleViewer,
}

func (e ProjectRole) IsValid() bool {
	switch e {
	case ProjectRoleAdmin, ProjectRoleMember, ProjectRoleViewer:
		return true
	}
	return false
}

func (e ProjectRole) String() string {
	return string(e)
}

func (e *ProjectRole) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ProjectRole(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ProjectRole", str)
	}
	return nil
}

func (e ProjectRole) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ProjectRole) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ProjectRole) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
