package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"chick/internal/events"
	"chick/internal/models"
	"context"
	"errors"
	"fmt"
	"time"
)

// RegisterAgent is the resolver for the registerAgent field.
func (r *mutationResolver) RegisterAgent(ctx context.Context, name string, kind AgentKind, externalID string, secret string, capabilities []string, deviceInfo *string, modelInfo *string) (*RegisterResult, error) {
	caps := capabilities
	if caps == nil {
		caps = []string{}
	}
	di, mi := "", ""
	if deviceInfo != nil {
		di = *deviceInfo
	}
	if modelInfo != nil {
		mi = *modelInfo
	}
	a, err := r.AgentSvc.Register(name, models.AgentKind(kind), externalID, secret, caps, di, mi)
	if err != nil {
		return nil, fmt.Errorf("register agent: %w", err)
	}

	loginResult, err := r.AgentSvc.Login(externalID, secret)
	if err != nil {
		return nil, fmt.Errorf("register agent: %w", err)
	}
	return &RegisterResult{
		Agent: agentFromModel(a),
		Token: loginResult.Token,
	}, nil
}

// LoginAgent is the resolver for the loginAgent field.
func (r *mutationResolver) LoginAgent(ctx context.Context, externalID string, secret string) (*LoginResult, error) {
	result, err := r.AgentSvc.Login(externalID, secret)
	if err != nil {
		return nil, fmt.Errorf("login: %w", err)
	}
	return &LoginResult{
		Agent: agentFromModel(result.Agent),
		Token: result.Token,
	}, nil
}

// UpdateAgentStatus is the resolver for the updateAgentStatus field.
func (r *mutationResolver) UpdateAgentStatus(ctx context.Context, id string, status AgentStatus) (*Agent, error) {
	if err := r.AgentSvc.UpdateStatus(parseID(id), models.AgentStatus(status)); err != nil {
		return nil, fmt.Errorf("update agent status: %w", err)
	}
	a, err := r.AgentSvc.GetByID(parseID(id))
	if err != nil {
		return nil, err
	}
	return agentFromModel(a), nil
}

// UpdateAgentAllowedCIDRs is the resolver for the updateAgentAllowedCIDRs field.
func (r *mutationResolver) UpdateAgentAllowedCIDRs(ctx context.Context, id string, allowedCIDRs []string) (*Agent, error) {
	if err := r.AgentSvc.UpdateAllowedCIDRs(parseID(id), allowedCIDRs); err != nil {
		return nil, fmt.Errorf("update agent allowed CIDRs: %w", err)
	}
	a, err := r.AgentSvc.GetByID(parseID(id))
	if err != nil {
		return nil, err
	}
	return agentFromModel(a), nil
}

// CreateProjectAgent is the resolver for the createProjectAgent field.
func (r *mutationResolver) CreateProjectAgent(ctx context.Context, projectID string, name string, kind AgentKind, externalID *string, secret *string, capabilities []string, deviceInfo *string, modelInfo *string) (*RegisterResult, error) {
	caps := capabilities
	if caps == nil {
		caps = []string{}
	}
	di, mi := "", ""
	if deviceInfo != nil {
		di = *deviceInfo
	}
	if modelInfo != nil {
		mi = *modelInfo
	}

	// Auto-generate externalID if not provided
	extID := name
	if externalID != nil && *externalID != "" {
		extID = *externalID
	} else {
		extID = extID + "-" + randomHex(4)
	}

	// Auto-generate secret if not provided
	pw := ""
	if secret != nil && *secret != "" {
		pw = *secret
	} else {
		pw = randomHex(16)
	}

	a, err := r.AgentSvc.Register(name, models.AgentKind(kind), extID, pw, caps, di, mi)
	if err != nil {
		return nil, fmt.Errorf("register agent: %w", err)
	}

	if _, err := r.ProjectSvc.AddMember(parseID(projectID), a.ID, models.ProjectRoleMember); err != nil {
		return nil, fmt.Errorf("add project member: %w", err)
	}

	return &RegisterResult{
		Agent: agentFromModel(a),
		Token: a.Token,
	}, nil
}

// CreateProject is the resolver for the createProject field.
func (r *mutationResolver) CreateProject(ctx context.Context, name string, description *string) (*Project, error) {
	agentID, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}
	desc := ""
	if description != nil {
		desc = *description
	}
	p, err := r.ProjectSvc.Create(name, desc)
	if err != nil {
		return nil, fmt.Errorf("create project: %w", err)
	}
	// Auto-add creator as project owner
	if _, err := r.ProjectSvc.AddMember(p.ID, agentID, models.ProjectRoleOwner); err != nil {
		return nil, fmt.Errorf("create project: add owner: %w", err)
	}
	return projectFromModel(p), nil
}

// UpdateProject is the resolver for the updateProject field.
func (r *mutationResolver) UpdateProject(ctx context.Context, id string, name *string, description *string) (*Project, error) {
	pid := parseID(id)
	if _, err := r.requireProjectOwner(ctx, pid); err != nil {
		return nil, err
	}
	n := ""
	if name != nil {
		n = *name
	}
	d := ""
	if description != nil {
		d = *description
	}
	p, err := r.ProjectSvc.Update(pid, n, d)
	if err != nil {
		return nil, fmt.Errorf("update project: %w", err)
	}
	return projectFromModel(p), nil
}

// DeleteProject is the resolver for the deleteProject field.
func (r *mutationResolver) DeleteProject(ctx context.Context, id string) (bool, error) {
	pid := parseID(id)
	if _, err := r.requireProjectOwner(ctx, pid); err != nil {
		return false, err
	}
	if err := r.ProjectSvc.Delete(pid); err != nil {
		return false, fmt.Errorf("delete project: %w", err)
	}
	return true, nil
}

// AddProjectMember is the resolver for the addProjectMember field.
func (r *mutationResolver) AddProjectMember(ctx context.Context, projectID string, agentID string, role ProjectRole) (*ProjectMember, error) {
	pid := parseID(projectID)
	if _, err := r.requireProjectOwner(ctx, pid); err != nil {
		return nil, err
	}
	m, err := r.ProjectSvc.AddMember(pid, parseID(agentID), models.ProjectRole(role))
	if err != nil {
		return nil, fmt.Errorf("add project member: %w", err)
	}
	return projectMemberFromModel(m), nil
}

// UpdateProjectMember is the resolver for the updateProjectMember field.
func (r *mutationResolver) UpdateProjectMember(ctx context.Context, projectID string, agentID string, role ProjectRole) (*ProjectMember, error) {
	pid := parseID(projectID)
	if _, err := r.requireProjectOwner(ctx, pid); err != nil {
		return nil, err
	}
	m, err := r.ProjectSvc.UpdateMember(pid, parseID(agentID), models.ProjectRole(role))
	if err != nil {
		return nil, fmt.Errorf("update project member: %w", err)
	}
	return projectMemberFromModel(m), nil
}

// RemoveProjectMember is the resolver for the removeProjectMember field.
func (r *mutationResolver) RemoveProjectMember(ctx context.Context, projectID string, agentID string) (bool, error) {
	pid := parseID(projectID)
	if _, err := r.requireProjectOwner(ctx, pid); err != nil {
		return false, err
	}
	if err := r.ProjectSvc.RemoveMember(pid, parseID(agentID)); err != nil {
		return false, fmt.Errorf("remove project member: %w", err)
	}
	return true, nil
}

// CreateIssue is the resolver for the createIssue field.
func (r *mutationResolver) CreateIssue(ctx context.Context, projectID string, title string, description *string, priority Priority, assigneeIDs []string, labelIDs []string, milestoneID *string) (*Issue, error) {
	pid := parseID(projectID)
	agentID, err := r.requireIssueProjectMemberByProject(ctx, pid)
	if err != nil {
		return nil, err
	}
	desc := ""
	if description != nil {
		desc = *description
	}
	assigneeUintIDs := make([]uint, len(assigneeIDs))
	for i, id := range assigneeIDs {
		assigneeUintIDs[i] = parseID(id)
	}
	labelUintIDs := make([]uint, len(labelIDs))
	for i, id := range labelIDs {
		labelUintIDs[i] = parseID(id)
	}
	var mid *uint
	if milestoneID != nil && *milestoneID != "" {
		v := parseID(*milestoneID)
		mid = &v
	}
	issue, err := r.IssueSvc.Create(pid, agentID, title, desc, models.Priority(priority), assigneeUintIDs, labelUintIDs, mid)
	if err != nil {
		return nil, fmt.Errorf("create issue: %w", err)
	}
	return issueFromModel(issue), nil
}

// UpdateIssue is the resolver for the updateIssue field.
func (r *mutationResolver) UpdateIssue(ctx context.Context, id string, title *string, description *string, priority *Priority, dueDate *time.Time, milestoneID *string) (*Issue, error) {
	iid := parseID(id)
	if _, err := r.requireIssueProjectMember(ctx, iid); err != nil {
		return nil, err
	}
	t := ""
	if title != nil {
		t = *title
	}
	d := ""
	if description != nil {
		d = *description
	}
	p := models.Priority("")
	if priority != nil {
		p = models.Priority(*priority)
	}
	var nt *models.UnixNullTime
	if dueDate != nil {
		nt = &models.UnixNullTime{Time: *dueDate, Valid: true}
	}
	var mid *uint
	if milestoneID != nil && *milestoneID != "" {
		v := parseID(*milestoneID)
		mid = &v
	}
	issue, err := r.IssueSvc.Update(iid, t, d, p, nt, mid)
	if err != nil {
		return nil, fmt.Errorf("update issue: %w", err)
	}
	return issueFromModel(issue), nil
}

// DeleteIssue is the resolver for the deleteIssue field.
func (r *mutationResolver) DeleteIssue(ctx context.Context, id string) (bool, error) {
	iid := parseID(id)
	if _, err := r.requireIssueProjectMember(ctx, iid); err != nil {
		return false, err
	}
	if err := r.IssueSvc.Delete(iid); err != nil {
		return false, fmt.Errorf("delete issue: %w", err)
	}
	return true, nil
}

// TransitionIssue is the resolver for the transitionIssue field.
func (r *mutationResolver) TransitionIssue(ctx context.Context, id string, newState IssueState, actorID string) (*Issue, error) {
	iid := parseID(id)
	agentID, err := r.requireIssueProjectMember(ctx, iid)
	if err != nil {
		return nil, err
	}
	if parseID(actorID) != agentID {
		return nil, errors.New("actorID 与认证身份不匹配")
	}
	issue, err := r.WorkflowSvc.Transition(iid, models.IssueState(newState), agentID)
	if err != nil {
		return nil, fmt.Errorf("transition issue: %w", err)
	}
	return issueFromModel(issue), nil
}

// AddAssignee is the resolver for the addAssignee field.
func (r *mutationResolver) AddAssignee(ctx context.Context, issueID string, agentID string) (*IssueAssignee, error) {
	iid := parseID(issueID)
	if _, err := r.requireIssueProjectMember(ctx, iid); err != nil {
		return nil, err
	}
	ia, err := r.IssueSvc.AddAssignee(iid, parseID(agentID))
	if err != nil {
		return nil, fmt.Errorf("add assignee: %w", err)
	}
	return issueAssigneeFromModel(ia), nil
}

// RemoveAssignee is the resolver for the removeAssignee field.
func (r *mutationResolver) RemoveAssignee(ctx context.Context, issueID string, agentID string) (bool, error) {
	iid := parseID(issueID)
	if _, err := r.requireIssueProjectMember(ctx, iid); err != nil {
		return false, err
	}
	if err := r.IssueSvc.RemoveAssignee(iid, parseID(agentID)); err != nil {
		return false, fmt.Errorf("remove assignee: %w", err)
	}
	return true, nil
}

// UpdateAssigneeState is the resolver for the updateAssigneeState field.
func (r *mutationResolver) UpdateAssigneeState(ctx context.Context, issueID string, agentID string, state AssigneeState) (*IssueAssignee, error) {
	iid := parseID(issueID)
	if _, err := r.requireIssueProjectMember(ctx, iid); err != nil {
		return nil, err
	}
	ia, err := r.IssueSvc.UpdateAssigneeState(iid, parseID(agentID), models.AssigneeState(state))
	if err != nil {
		return nil, fmt.Errorf("update assignee state: %w", err)
	}
	return issueAssigneeFromModel(ia), nil
}

// AddComment is the resolver for the addComment field.
func (r *mutationResolver) AddComment(ctx context.Context, issueID string, authorID string, body string, contentType CommentContentType, parentID *string) (*Comment, error) {
	iid := parseID(issueID)
	agentID, err := r.requireIssueProjectMember(ctx, iid)
	if err != nil {
		return nil, err
	}
	if parseID(authorID) != agentID {
		return nil, errors.New("authorID 与认证身份不匹配")
	}
	var pid *uint
	if parentID != nil {
		v := parseID(*parentID)
		pid = &v
	}
	c, err := r.CommentSvc.Create(iid, agentID, body, models.CommentContentType(contentType), pid)
	if err != nil {
		return nil, fmt.Errorf("add comment: %w", err)
	}
	return commentFromModel(c), nil
}

// UpdateComment is the resolver for the updateComment field.
func (r *mutationResolver) UpdateComment(ctx context.Context, id string, body string) (*Comment, error) {
	agentID, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}
	c, err := r.CommentSvc.GetByID(parseID(id))
	if err != nil {
		return nil, fmt.Errorf("comment not found")
	}
	if c.AuthorID != agentID {
		return nil, errors.New("只能编辑自己的评论")
	}
	c, err = r.CommentSvc.Update(parseID(id), body)
	if err != nil {
		return nil, fmt.Errorf("update comment: %w", err)
	}
	return commentFromModel(c), nil
}

// DeleteComment is the resolver for the deleteComment field.
func (r *mutationResolver) DeleteComment(ctx context.Context, id string) (bool, error) {
	agentID, err := requireAuth(ctx)
	if err != nil {
		return false, err
	}
	c, err := r.CommentSvc.GetByID(parseID(id))
	if err != nil {
		return false, fmt.Errorf("comment not found")
	}
	if c.AuthorID != agentID {
		return false, errors.New("只能删除自己的评论")
	}
	if err := r.CommentSvc.Delete(parseID(id)); err != nil {
		return false, fmt.Errorf("delete comment: %w", err)
	}
	return true, nil
}

// AddLabels is the resolver for the addLabels field.
func (r *mutationResolver) AddLabels(ctx context.Context, issueID string, labelIDs []string) (*Issue, error) {
	iid := parseID(issueID)
	if _, err := r.requireIssueProjectMember(ctx, iid); err != nil {
		return nil, err
	}
	for _, lid := range labelIDs {
		if err := r.IssueSvc.AddLabel(iid, parseID(lid)); err != nil {
			return nil, fmt.Errorf("add label: %w", err)
		}
	}
	issue, err := r.IssueSvc.GetByID(iid)
	if err != nil {
		return nil, err
	}
	return issueFromModel(issue), nil
}

// RemoveLabels is the resolver for the removeLabels field.
func (r *mutationResolver) RemoveLabels(ctx context.Context, issueID string, labelIDs []string) (*Issue, error) {
	iid := parseID(issueID)
	if _, err := r.requireIssueProjectMember(ctx, iid); err != nil {
		return nil, err
	}
	for _, lid := range labelIDs {
		if err := r.IssueSvc.RemoveLabel(iid, parseID(lid)); err != nil {
			return nil, fmt.Errorf("remove label: %w", err)
		}
	}
	issue, err := r.IssueSvc.GetByID(iid)
	if err != nil {
		return nil, err
	}
	return issueFromModel(issue), nil
}

// CreateLabel is the resolver for the createLabel field.
func (r *mutationResolver) CreateLabel(ctx context.Context, projectID string, name string, color *string, capability *string, group *string) (*Label, error) {
	pid := parseID(projectID)
	if _, err := r.requireProjectOwner(ctx, pid); err != nil {
		return nil, err
	}
	c := ""
	if color != nil {
		c = *color
	}
	cap := ""
	if capability != nil {
		cap = *capability
	}
	g := ""
	if group != nil {
		g = *group
	}
	l, err := r.ProjectSvc.CreateLabel(pid, name, c, cap, g)
	if err != nil {
		return nil, fmt.Errorf("create label: %w", err)
	}
	return labelFromModel(l), nil
}

// DeleteLabel is the resolver for the deleteLabel field.
func (r *mutationResolver) DeleteLabel(ctx context.Context, id string) (bool, error) {
	label, err := r.ProjectSvc.GetLabelByID(parseID(id))
	if err != nil {
		return false, fmt.Errorf("标签不存在")
	}
	if _, err := r.requireProjectOwner(ctx, label.ProjectID); err != nil {
		return false, err
	}
	if err := r.ProjectSvc.DeleteLabel(parseID(id)); err != nil {
		return false, fmt.Errorf("delete label: %w", err)
	}
	return true, nil
}

// CreateMilestone is the resolver for the createMilestone field.
func (r *mutationResolver) CreateMilestone(ctx context.Context, projectID string, title string, description *string, dueDate *time.Time) (*Milestone, error) {
	pid := parseID(projectID)
	if _, err := r.requireProjectOwner(ctx, pid); err != nil {
		return nil, err
	}
	d := ""
	if description != nil {
		d = *description
	}
	var nt *models.UnixNullTime
	if dueDate != nil {
		nt = &models.UnixNullTime{Time: *dueDate, Valid: true}
	}
	m, err := r.ProjectSvc.CreateMilestone(pid, title, d, nt)
	if err != nil {
		return nil, fmt.Errorf("create milestone: %w", err)
	}
	return milestoneFromModel(m), nil
}

// DeleteMilestone is the resolver for the deleteMilestone field.
func (r *mutationResolver) DeleteMilestone(ctx context.Context, id string) (bool, error) {
	milestone, err := r.ProjectSvc.GetMilestoneByID(parseID(id))
	if err != nil {
		return false, fmt.Errorf("里程碑不存在")
	}
	if _, err := r.requireProjectOwner(ctx, milestone.ProjectID); err != nil {
		return false, err
	}
	if err := r.ProjectSvc.DeleteMilestone(parseID(id)); err != nil {
		return false, fmt.Errorf("delete milestone: %w", err)
	}
	return true, nil
}

// CreateFeedback is the resolver for the createFeedback field.
func (r *mutationResolver) CreateFeedback(ctx context.Context, targetType FeedbackTargetType, targetID string, authorID string, rating FeedbackRating, body *string) (*Feedback, error) {
	agentID, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}
	if parseID(authorID) != agentID {
		return nil, errors.New("authorID 与认证身份不匹配")
	}
	b := ""
	if body != nil {
		b = *body
	}
	f, err := r.FeedbackSvc.Create(models.FeedbackTargetType(targetType), parseID(targetID), agentID, feedbackRatingToInt(rating), b)
	if err != nil {
		return nil, fmt.Errorf("create feedback: %w", err)
	}
	return feedbackFromModel(f), nil
}

// Agents is the resolver for the agents field.
func (r *queryResolver) Agents(ctx context.Context, kind *AgentKind, status *AgentStatus, capabilities []string, projectID *string) ([]*Agent, error) {
	if _, err := requireAuth(ctx); err != nil {
		return nil, err
	}
	filter := models.AgentFilter{}
	if kind != nil {
		k := models.AgentKind(*kind)
		filter.Kind = &k
	}
	if status != nil {
		s := models.AgentStatus(*status)
		filter.Status = &s
	}
	if projectID != nil {
		pid := parseID(*projectID)
		filter.ProjectID = &pid
	}
	if len(capabilities) > 0 {
		caps := make([]models.CapabilityType, len(capabilities))
		for i, c := range capabilities {
			caps[i] = models.CapabilityType(c)
		}
		filter.Capabilities = caps
	}
	agents, err := r.AgentSvc.List(filter)
	if err != nil {
		return nil, fmt.Errorf("list agents: %w", err)
	}
	result := make([]*Agent, len(agents))
	for i, a := range agents {
		result[i] = agentFromModel(&a)
	}
	return result, nil
}

// Agent is the resolver for the agent field.
func (r *queryResolver) Agent(ctx context.Context, id string) (*Agent, error) {
	if _, err := requireAuth(ctx); err != nil {
		return nil, err
	}
	a, err := r.AgentSvc.GetByID(parseID(id))
	if err != nil {
		return nil, fmt.Errorf("get agent: %w", err)
	}
	return agentFromModel(a), nil
}

// Projects is the resolver for the projects field.
func (r *queryResolver) Projects(ctx context.Context) ([]*Project, error) {
	agentID, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}
	projects, err := r.ProjectSvc.ListByAgent(agentID)
	if err != nil {
		return nil, fmt.Errorf("list projects: %w", err)
	}
	result := make([]*Project, len(projects))
	for i, p := range projects {
		result[i] = projectFromModel(&p)
	}
	return result, nil
}

// Project is the resolver for the project field.
func (r *queryResolver) Project(ctx context.Context, id string) (*Project, error) {
	pid := parseID(id)
	if _, err := r.requireProjectMember(ctx, pid); err != nil {
		return nil, err
	}
	p, err := r.ProjectSvc.GetByID(pid)
	if err != nil {
		return nil, fmt.Errorf("get project: %w", err)
	}
	return projectFromModel(p), nil
}

// Labels is the resolver for the labels field.
func (r *queryResolver) Labels(ctx context.Context, projectID string, group *string) ([]*Label, error) {
	pid := parseID(projectID)
	if _, err := r.requireProjectMember(ctx, pid); err != nil {
		return nil, err
	}
	g := ""
	if group != nil {
		g = *group
	}
	labels, err := r.ProjectSvc.ListLabels(pid, g)
	if err != nil {
		return nil, fmt.Errorf("list labels: %w", err)
	}
	result := make([]*Label, len(labels))
	for i, l := range labels {
		result[i] = labelFromModel(&l)
	}
	return result, nil
}

// Milestones is the resolver for the milestones field.
func (r *queryResolver) Milestones(ctx context.Context, projectID string, state *MilestoneState) ([]*Milestone, error) {
	pid := parseID(projectID)
	if _, err := r.requireProjectMember(ctx, pid); err != nil {
		return nil, err
	}
	s := models.MilestoneState("")
	if state != nil {
		s = models.MilestoneState(*state)
	}
	milestones, err := r.ProjectSvc.ListMilestones(pid, s)
	if err != nil {
		return nil, fmt.Errorf("list milestones: %w", err)
	}
	result := make([]*Milestone, len(milestones))
	for i, m := range milestones {
		result[i] = milestoneFromModel(&m)
	}
	return result, nil
}

// Issue is the resolver for the issue field.
func (r *queryResolver) Issue(ctx context.Context, id string) (*Issue, error) {
	iid := parseID(id)
	if _, err := r.requireIssueProjectMember(ctx, iid); err != nil {
		return nil, err
	}
	issue, err := r.IssueSvc.GetByID(iid)
	if err != nil {
		return nil, fmt.Errorf("get issue: %w", err)
	}
	return issueFromModel(issue), nil
}

// Issues is the resolver for the issues field.
func (r *queryResolver) Issues(ctx context.Context, projectID string, state *IssueState, priority *Priority, assigneeID *string, limit *int32, offset *int32) (*IssueConnection, error) {
	pid := parseID(projectID)
	if _, err := r.requireProjectMember(ctx, pid); err != nil {
		return nil, err
	}
	filter := models.IssueFilter{ProjectID: uintPtr(pid)}
	if state != nil {
		filter.State = []models.IssueState{models.IssueState(*state)}
	}
	if priority != nil {
		p := models.Priority(*priority)
		filter.Priority = &p
	}
	if assigneeID != nil {
		filter.AssigneeIDs = []uint{parseID(*assigneeID)}
	}
	if limit != nil {
		filter.Limit = int(*limit)
	}
	if offset != nil {
		filter.Offset = int(*offset)
	}

	issues, total, err := r.IssueSvc.List(filter)
	if err != nil {
		return nil, fmt.Errorf("list issues: %w", err)
	}
	result := make([]*Issue, len(issues))
	for i, iss := range issues {
		result[i] = issueFromModel(&iss)
	}
	return &IssueConnection{
		Edges: result,
		Total: int32(total),
	}, nil
}

// Comments is the resolver for the comments field.
func (r *queryResolver) Comments(ctx context.Context, issueID string) ([]*Comment, error) {
	iid := parseID(issueID)
	if _, err := r.requireIssueProjectMember(ctx, iid); err != nil {
		return nil, err
	}
	comments, err := r.CommentSvc.ListByIssue(iid)
	if err != nil {
		return nil, fmt.Errorf("list comments: %w", err)
	}
	result := make([]*Comment, len(comments))
	for i, c := range comments {
		result[i] = commentFromModel(&c)
	}
	return result, nil
}

// Timeline is the resolver for the timeline field.
func (r *queryResolver) Timeline(ctx context.Context, issueID string) ([]*TimelineEvent, error) {
	iid := parseID(issueID)
	if _, err := r.requireIssueProjectMember(ctx, iid); err != nil {
		return nil, err
	}
	events, err := r.IssueSvc.ListTimeline(iid)
	if err != nil {
		return nil, fmt.Errorf("list timeline: %w", err)
	}
	result := make([]*TimelineEvent, len(events))
	for i, e := range events {
		result[i] = timelineFromModel(&e)
	}
	return result, nil
}

// ValidTransitions is the resolver for the validTransitions field.
func (r *queryResolver) ValidTransitions(ctx context.Context, state IssueState) ([]IssueState, error) {
	states, err := r.WorkflowSvc.ValidTransitions(models.IssueState(state))
	if err != nil {
		return nil, fmt.Errorf("valid transitions: %w", err)
	}
	result := make([]IssueState, len(states))
	for i, s := range states {
		result[i] = IssueState(s)
	}
	return result, nil
}

// Feedback is the resolver for the feedback field.
func (r *queryResolver) Feedback(ctx context.Context, targetType FeedbackTargetType, targetID string) ([]*Feedback, error) {
	if _, err := requireAuth(ctx); err != nil {
		return nil, err
	}
	list, err := r.FeedbackSvc.ListByTarget(models.FeedbackTargetType(targetType), parseID(targetID))
	if err != nil {
		return nil, fmt.Errorf("list feedback: %w", err)
	}
	result := make([]*Feedback, len(list))
	for i, f := range list {
		result[i] = feedbackFromModel(&f)
	}
	return result, nil
}

// IssueUpdated is the resolver for the issueUpdated field.
func (r *subscriptionResolver) IssueUpdated(ctx context.Context, issueID string) (<-chan *Issue, error) {
	ch := make(chan *Issue, 1)
	id := parseID(issueID)

	// Publish initial state
	issue, err := r.IssueSvc.GetByID(id)
	if err == nil {
		ch <- issueFromModel(issue)
	}

	cancel := func() {}
	if r.EventBus != nil {
		cancel = r.EventBus.Subscribe(events.EventIssueStateChanged, func(evt events.Event) {
			payload, ok := evt.Payload.(events.IssueStateChangedPayload)
			if !ok {
				return
			}
			if payload.IssueID == id {
				issue, err := r.IssueSvc.GetByID(id)
				if err == nil {
					select {
					case ch <- issueFromModel(issue):
					default:
					}
				}
			}
		})
	}

	go func() {
		<-ctx.Done()
		cancel()
		close(ch)
	}()

	return ch, nil
}

// AgentNotifications is the resolver for the agentNotifications field.
func (r *subscriptionResolver) AgentNotifications(ctx context.Context, agentID string) (<-chan *NotificationEvent, error) {
	ch := make(chan *NotificationEvent, 5)
	id := parseID(agentID)

	cancel1 := func() {}
	cancel2 := func() {}
	if r.EventBus != nil {
		cancel1 = r.EventBus.Subscribe(events.EventIssueAssigneeChanged, func(evt events.Event) {
			payload, ok := evt.Payload.(events.IssueAssigneeChangedPayload)
			if !ok {
				return
			}
			if payload.AgentID == id {
				msg := "You have been assigned to an issue"
				if payload.Action == "removed" {
					msg = "You have been unassigned from an issue"
				}
				select {
				case ch <- &NotificationEvent{
					ID:               fmt.Sprintf("notif-%d", time.Now().UnixNano()),
					NotificationType: "assignee_changed",
					Message:          msg,
					Read:             false,
					CreatedAt:        time.Now(),
				}:
				default:
				}
			}
		})

		cancel2 = r.EventBus.Subscribe(events.EventCommentAdded, func(evt events.Event) {
			_, ok := evt.Payload.(events.CommentAddedPayload)
			if !ok {
				return
			}
			select {
			case ch <- &NotificationEvent{
				ID:               fmt.Sprintf("notif-%d", time.Now().UnixNano()),
				NotificationType: "comment_added",
				Message:          "New comment on an issue",
				Read:             false,
				CreatedAt:        time.Now(),
			}:
			default:
			}
		})
	}

	go func() {
		<-ctx.Done()
		cancel1()
		cancel2()
		close(ch)
	}()

	return ch, nil
}

// AgentStatusChanged is the resolver for the agentStatusChanged field.
func (r *subscriptionResolver) AgentStatusChanged(ctx context.Context) (<-chan *AgentStatusEvent, error) {
	ch := make(chan *AgentStatusEvent, 5)

	cancel := func() {}
	if r.EventBus != nil {
		cancel = r.EventBus.Subscribe(events.EventAgentStatusChanged, func(evt events.Event) {
			payload, ok := evt.Payload.(events.AgentStatusChangedPayload)
			if !ok {
				return
			}
			select {
			case ch <- &AgentStatusEvent{
				AgentID:   formatID(payload.AgentID),
				Status:    AgentStatus(models.AgentStatus(payload.Status)),
				Timestamp: time.Now(),
			}:
			default:
			}
		})
	}

	go func() {
		<-ctx.Done()
		cancel()
		close(ch)
	}()

	return ch, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
