package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"chick/internal/auth"
	"chick/internal/events"
	"chick/internal/models"
	"context"
	"errors"
	"fmt"
	"time"
)

// RegisterAgent is the resolver for the registerAgent field.
func (r *mutationResolver) RegisterAgent(ctx context.Context, name string, kind AgentKind, externalID string, secret string, capabilities []string, deviceInfo *string, modelInfo *string) (*RegisterResult, error) {
	caps := capabilities
	if caps == nil {
		caps = []string{}
	}
	di, mi := "", ""
	if deviceInfo != nil {
		di = *deviceInfo
	}
	if modelInfo != nil {
		mi = *modelInfo
	}
	a, err := r.AgentSvc.Register(name, models.AgentKind(kind), externalID, secret, caps, di, mi)
	if err != nil {
		return nil, fmt.Errorf("register agent: %w", err)
	}

	loginResult, err := r.AgentSvc.Login(externalID, secret)
	if err != nil {
		return nil, fmt.Errorf("register agent: %w", err)
	}
	return &RegisterResult{
		Agent: agentFromModel(a),
		Token: loginResult.Token,
	}, nil
}

// LoginAgent is the resolver for the loginAgent field.
func (r *mutationResolver) LoginAgent(ctx context.Context, externalID string, secret string) (*LoginResult, error) {
	// Rate limit: 10 attempts per 15 minutes per IP
	ip := auth.ClientIPFromContext(ctx)
	if ip != "" && !r.LoginLimiter.Allow(ip) {
		return nil, fmt.Errorf("login: too many attempts, please try again later")
	}

	result, err := r.AgentSvc.Login(externalID, secret)
	if err != nil {
		return nil, fmt.Errorf("login: %w", err)
	}
	return &LoginResult{
		Agent: agentFromModel(result.Agent),
		Token: result.Token,
	}, nil
}

// UpdateAgentStatus is the resolver for the updateAgentStatus field.
func (r *mutationResolver) UpdateAgentStatus(ctx context.Context, id string, status AgentStatus) (*Agent, error) {
	if _, err := requireSelfAccess(ctx, parseID(id)); err != nil {
		return nil, err
	}
	if err := r.AgentSvc.UpdateStatus(parseID(id), models.AgentStatus(status)); err != nil {
		return nil, fmt.Errorf("update agent status: %w", err)
	}
	a, err := r.AgentSvc.GetByID(parseID(id))
	if err != nil {
		return nil, err
	}
	return agentFromModel(a), nil
}

// UpdateAgentDisabled is the resolver for the updateAgentDisabled field.
func (r *mutationResolver) UpdateAgentDisabled(ctx context.Context, id string, disabled bool) (*Agent, error) {
	if _, err := requireSelfAccess(ctx, parseID(id)); err != nil {
		return nil, err
	}
	if err := r.AgentSvc.SetDisabled(parseID(id), disabled); err != nil {
		return nil, fmt.Errorf("update agent disabled: %w", err)
	}
	a, err := r.AgentSvc.GetByID(parseID(id))
	if err != nil {
		return nil, err
	}
	return agentFromModel(a), nil
}

// UpdateAgent is the resolver for the updateAgent field.
func (r *mutationResolver) UpdateAgent(ctx context.Context, id string, systemPrompt *string) (*Agent, error) {
	if _, err := requireSelfAccess(ctx, parseID(id)); err != nil {
		return nil, err
	}
	sp := ""
	if systemPrompt != nil {
		sp = *systemPrompt
	}
	if err := r.AgentSvc.Update(parseID(id), sp); err != nil {
		return nil, fmt.Errorf("update agent: %w", err)
	}
	a, err := r.AgentSvc.GetByID(parseID(id))
	if err != nil {
		return nil, err
	}
	return agentFromModel(a), nil
}

// DeleteAgent is the resolver for the deleteAgent field.
func (r *mutationResolver) DeleteAgent(ctx context.Context, id string) (bool, error) {
	if _, err := requireSelfAccess(ctx, parseID(id)); err != nil {
		return false, err
	}
	if err := r.AgentSvc.Delete(parseID(id)); err != nil {
		return false, err
	}
	return true, nil
}

// UpdateAgentAllowedCIDRs is the resolver for the updateAgentAllowedCIDRs field.
func (r *mutationResolver) UpdateAgentAllowedCIDRs(ctx context.Context, id string, allowedCIDRs []string) (*Agent, error) {
	if _, err := requireSelfAccess(ctx, parseID(id)); err != nil {
		return nil, err
	}
	if err := r.AgentSvc.UpdateAllowedCIDRs(parseID(id), allowedCIDRs); err != nil {
		return nil, fmt.Errorf("update agent allowed CIDRs: %w", err)
	}
	a, err := r.AgentSvc.GetByID(parseID(id))
	if err != nil {
		return nil, err
	}
	return agentFromModel(a), nil
}

// CreateProjectAgent is the resolver for the createProjectAgent field.
func (r *mutationResolver) CreateProjectAgent(ctx context.Context, projectID string, name string, kind AgentKind, role *ProjectRole, externalID *string, secret *string, capabilities []string, deviceInfo *string, modelInfo *string) (*RegisterResult, error) {
	pid := parseID(projectID)
	if _, err := r.requireProjectOwner(ctx, pid); err != nil {
		return nil, err
	}
	caps := capabilities
	if caps == nil {
		caps = []string{}
	}
	di, mi := "", ""
	if deviceInfo != nil {
		di = *deviceInfo
	}
	if modelInfo != nil {
		mi = *modelInfo
	}

	// Auto-generate externalID if not provided
	extID := name
	if externalID != nil && *externalID != "" {
		extID = *externalID
	} else {
		extID = extID + "-" + randomHex(4)
	}

	// Auto-generate secret if not provided
	pw := ""
	if secret != nil && *secret != "" {
		pw = *secret
	} else {
		pw = randomHex(16)
	}

	a, err := r.AgentSvc.Register(name, models.AgentKind(kind), extID, pw, caps, di, mi)
	if err != nil {
		return nil, fmt.Errorf("register agent: %w", err)
	}

	projectRole := models.ProjectRoleMember
	if role != nil {
		projectRole = models.ProjectRole(*role)
	}
	if _, err := r.ProjectSvc.AddMember(pid, a.ID, projectRole); err != nil {
		return nil, fmt.Errorf("add project member: %w", err)
	}

	return &RegisterResult{
		Agent: agentFromModel(a),
		Token: a.Token,
	}, nil
}

// CreateProject is the resolver for the createProject field.
func (r *mutationResolver) CreateProject(ctx context.Context, name string, description *string) (*Project, error) {
	agentID, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}
	desc := ""
	if description != nil {
		desc = *description
	}
	p, err := r.ProjectSvc.Create(name, desc)
	if err != nil {
		return nil, fmt.Errorf("create project: %w", err)
	}
	// Auto-add creator as project owner
	if _, err := r.ProjectSvc.AddMember(p.ID, agentID, models.ProjectRoleOwner); err != nil {
		return nil, fmt.Errorf("create project: add owner: %w", err)
	}
	return projectFromModel(p), nil
}

// UpdateProject is the resolver for the updateProject field.
func (r *mutationResolver) UpdateProject(ctx context.Context, id string, name *string, description *string) (*Project, error) {
	pid := parseID(id)
	if _, err := r.requireProjectOwner(ctx, pid); err != nil {
		return nil, err
	}
	n := ""
	if name != nil {
		n = *name
	}
	d := ""
	if description != nil {
		d = *description
	}
	p, err := r.ProjectSvc.Update(pid, n, d)
	if err != nil {
		return nil, fmt.Errorf("update project: %w", err)
	}
	return projectFromModel(p), nil
}

// UpdateProjectConfig is the resolver for the updateProjectConfig field.
func (r *mutationResolver) UpdateProjectConfig(ctx context.Context, id string, allowCreatorTransition *bool, requireCreatorCloseApproval *bool) (*Project, error) {
	pid := parseID(id)
	if _, err := r.requireProjectOwner(ctx, pid); err != nil {
		return nil, err
	}
	p, err := r.ProjectSvc.UpdateConfig(pid, allowCreatorTransition, requireCreatorCloseApproval)
	if err != nil {
		return nil, fmt.Errorf("update project config: %w", err)
	}
	return projectFromModel(p), nil
}

// DeleteProject is the resolver for the deleteProject field.
func (r *mutationResolver) DeleteProject(ctx context.Context, id string) (bool, error) {
	pid := parseID(id)
	if _, err := r.requireProjectOwner(ctx, pid); err != nil {
		return false, err
	}
	if err := r.ProjectSvc.Delete(pid); err != nil {
		return false, fmt.Errorf("delete project: %w", err)
	}
	return true, nil
}

// AddProjectMember is the resolver for the addProjectMember field.
func (r *mutationResolver) AddProjectMember(ctx context.Context, projectID string, agentID string, role ProjectRole) (*ProjectMember, error) {
	pid := parseID(projectID)
	if _, err := r.requireProjectOwner(ctx, pid); err != nil {
		return nil, err
	}
	m, err := r.ProjectSvc.AddMember(pid, parseID(agentID), models.ProjectRole(role))
	if err != nil {
		return nil, fmt.Errorf("add project member: %w", err)
	}
	return projectMemberFromModel(m), nil
}

// UpdateProjectMember is the resolver for the updateProjectMember field.
func (r *mutationResolver) UpdateProjectMember(ctx context.Context, projectID string, agentID string, role ProjectRole) (*ProjectMember, error) {
	pid := parseID(projectID)
	if _, err := r.requireProjectOwner(ctx, pid); err != nil {
		return nil, err
	}
	m, err := r.ProjectSvc.UpdateMember(pid, parseID(agentID), models.ProjectRole(role))
	if err != nil {
		return nil, fmt.Errorf("update project member: %w", err)
	}
	return projectMemberFromModel(m), nil
}

// RemoveProjectMember is the resolver for the removeProjectMember field.
func (r *mutationResolver) RemoveProjectMember(ctx context.Context, projectID string, agentID string) (bool, error) {
	pid := parseID(projectID)
	if _, err := r.requireProjectOwner(ctx, pid); err != nil {
		return false, err
	}
	if err := r.ProjectSvc.RemoveMember(pid, parseID(agentID)); err != nil {
		return false, fmt.Errorf("remove project member: %w", err)
	}
	return true, nil
}

// CreateIssue is the resolver for the createIssue field.
func (r *mutationResolver) CreateIssue(ctx context.Context, projectID string, title string, description *string, priority Priority, assigneeIDs []string, labelIDs []string, milestoneID *string, environment *string, branch *string, link *string) (*Issue, error) {
	pid := parseID(projectID)
	agentID, err := r.requireIssueProjectMemberByProject(ctx, pid)
	if err != nil {
		return nil, err
	}
	desc := ""
	if description != nil {
		desc = *description
	}
	assigneeUintIDs := make([]uint, len(assigneeIDs))
	for i, id := range assigneeIDs {
		assigneeUintIDs[i] = parseID(id)
	}
	labelUintIDs := make([]uint, len(labelIDs))
	for i, id := range labelIDs {
		labelUintIDs[i] = parseID(id)
	}
	var mid *uint
	if milestoneID != nil && *milestoneID != "" {
		v := parseID(*milestoneID)
		mid = &v
	}
	issue, err := r.IssueSvc.Create(pid, agentID, title, desc, models.Priority(priority), assigneeUintIDs, labelUintIDs, mid, environment, branch, link, nil, nil, nil)
	if err != nil {
		return nil, fmt.Errorf("create issue: %w", err)
	}
	return issueFromModel(issue), nil
}

// UpdateIssue is the resolver for the updateIssue field.
func (r *mutationResolver) UpdateIssue(ctx context.Context, id string, title *string, description *string, priority *Priority, dueDate *time.Time, milestoneID *string, environment *string, branch *string, link *string, startedAt *time.Time, completedAt *time.Time, difficulty *int32) (*Issue, error) {
	iid := parseID(id)
	if _, err := r.requireIssueProjectMember(ctx, iid); err != nil {
		return nil, err
	}
	t := ""
	if title != nil {
		t = *title
	}
	d := ""
	if description != nil {
		d = *description
	}
	p := models.Priority("")
	if priority != nil {
		p = models.Priority(*priority)
	}
	var nt *models.UnixNullTime
	if dueDate != nil {
		nt = &models.UnixNullTime{Time: *dueDate, Valid: true}
	}
	var mid *uint
	if milestoneID != nil {
		if *milestoneID != "" {
			v := parseID(*milestoneID)
			mid = &v
		} else {
			z := uint(0)
			mid = &z
		}
	}
	var diff *int
	if difficulty != nil {
		d := int(*difficulty)
		diff = &d
	}
	issue, err := r.IssueSvc.Update(iid, t, d, p, nt, mid, environment, branch, link, startedAt, completedAt, diff)
	if err != nil {
		return nil, fmt.Errorf("update issue: %w", err)
	}
	return issueFromModel(issue), nil
}

// DeleteIssue is the resolver for the deleteIssue field.
func (r *mutationResolver) DeleteIssue(ctx context.Context, id string) (bool, error) {
	iid := parseID(id)
	if _, err := r.requireIssueProjectMember(ctx, iid); err != nil {
		return false, err
	}
	if err := r.IssueSvc.Delete(iid); err != nil {
		return false, fmt.Errorf("delete issue: %w", err)
	}
	return true, nil
}

// TransitionIssue is the resolver for the transitionIssue field.
func (r *mutationResolver) TransitionIssue(ctx context.Context, id string, newState IssueState, actorID string, note *string) (*Issue, error) {
	iid := parseID(id)
	agentID, err := r.requireIssueProjectMember(ctx, iid)
	if err != nil {
		return nil, err
	}
	if parseID(actorID) != agentID {
		return nil, errors.New("actorID 与认证身份不匹配")
	}
	issue, err := r.WorkflowSvc.Transition(iid, models.IssueState(newState), agentID, note)
	if err != nil {
		return nil, fmt.Errorf("transition issue: %w", err)
	}
	return issueFromModel(issue), nil
}

// AddAssignee is the resolver for the addAssignee field.
func (r *mutationResolver) AddAssignee(ctx context.Context, issueID string, agentID string) (*IssueAssignee, error) {
	iid := parseID(issueID)
	if _, err := r.requireIssueProjectMember(ctx, iid); err != nil {
		return nil, err
	}
	ia, err := r.IssueSvc.AddAssignee(iid, parseID(agentID))
	if err != nil {
		return nil, fmt.Errorf("add assignee: %w", err)
	}
	return issueAssigneeFromModel(ia), nil
}

// RemoveAssignee is the resolver for the removeAssignee field.
func (r *mutationResolver) RemoveAssignee(ctx context.Context, issueID string, agentID string) (bool, error) {
	iid := parseID(issueID)
	if _, err := r.requireIssueProjectMember(ctx, iid); err != nil {
		return false, err
	}
	if err := r.IssueSvc.RemoveAssignee(iid, parseID(agentID)); err != nil {
		return false, fmt.Errorf("remove assignee: %w", err)
	}
	return true, nil
}

// UpdateAssigneeState is the resolver for the updateAssigneeState field.
func (r *mutationResolver) UpdateAssigneeState(ctx context.Context, issueID string, agentID string, state AssigneeState) (*IssueAssignee, error) {
	iid := parseID(issueID)
	if _, err := r.requireIssueProjectMember(ctx, iid); err != nil {
		return nil, err
	}
	ia, err := r.IssueSvc.UpdateAssigneeState(iid, parseID(agentID), models.AssigneeState(state))
	if err != nil {
		return nil, fmt.Errorf("update assignee state: %w", err)
	}
	return issueAssigneeFromModel(ia), nil
}

// AddComment is the resolver for the addComment field.
func (r *mutationResolver) AddComment(ctx context.Context, issueID string, authorID string, body string, contentType CommentContentType, parentID *string) (*Comment, error) {
	iid := parseID(issueID)
	agentID, err := r.requireIssueProjectMember(ctx, iid)
	if err != nil {
		return nil, err
	}
	if parseID(authorID) != agentID {
		return nil, errors.New("authorID 与认证身份不匹配")
	}
	var pid *uint
	if parentID != nil {
		v := parseID(*parentID)
		pid = &v
	}
	c, err := r.CommentSvc.Create(iid, agentID, body, models.CommentContentType(contentType), pid)
	if err != nil {
		return nil, fmt.Errorf("add comment: %w", err)
	}
	return commentFromModel(c), nil
}

// AddProposalComment is the resolver for the addProposalComment field.
func (r *mutationResolver) AddProposalComment(ctx context.Context, proposalID string, authorID string, body string, contentType CommentContentType) (*Comment, error) {
	pid := parseID(proposalID)
	agentID, err := r.requireProposalProjectMember(ctx, pid)
	if err != nil {
		return nil, err
	}
	if parseID(authorID) != agentID {
		return nil, errors.New("authorID 与认证身份不匹配")
	}
	c, err := r.CommentSvc.CreateForProposal(pid, agentID, body, models.CommentContentType(contentType), nil)
	if err != nil {
		return nil, fmt.Errorf("add proposal comment: %w", err)
	}
	return commentFromModel(c), nil
}

// AddTaskComment is the resolver for the addTaskComment field.
func (r *mutationResolver) AddTaskComment(ctx context.Context, taskID string, authorID string, body string, contentType CommentContentType) (*Comment, error) {
	tid := parseID(taskID)
	agentID, err := r.requireTaskProjectMember(ctx, tid)
	if err != nil {
		return nil, err
	}
	if parseID(authorID) != agentID {
		return nil, errors.New("authorID 与认证身份不匹配")
	}
	c, err := r.CommentSvc.CreateForTask(tid, agentID, body, models.CommentContentType(contentType), nil)
	if err != nil {
		return nil, fmt.Errorf("add task comment: %w", err)
	}
	return commentFromModel(c), nil
}

// UpdateComment is the resolver for the updateComment field.
func (r *mutationResolver) UpdateComment(ctx context.Context, id string, body string) (*Comment, error) {
	agentID, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}
	c, err := r.CommentSvc.GetByID(parseID(id))
	if err != nil {
		return nil, fmt.Errorf("comment not found")
	}
	if c.AuthorID != agentID {
		return nil, errors.New("只能编辑自己的评论")
	}
	c, err = r.CommentSvc.Update(parseID(id), body)
	if err != nil {
		return nil, fmt.Errorf("update comment: %w", err)
	}
	return commentFromModel(c), nil
}

// DeleteComment is the resolver for the deleteComment field.
func (r *mutationResolver) DeleteComment(ctx context.Context, id string) (bool, error) {
	agentID, err := requireAuth(ctx)
	if err != nil {
		return false, err
	}
	c, err := r.CommentSvc.GetByID(parseID(id))
	if err != nil {
		return false, fmt.Errorf("comment not found")
	}
	if c.AuthorID != agentID {
		return false, errors.New("只能删除自己的评论")
	}
	if err := r.CommentSvc.Delete(parseID(id)); err != nil {
		return false, fmt.Errorf("delete comment: %w", err)
	}
	return true, nil
}

// AddLabels is the resolver for the addLabels field.
func (r *mutationResolver) AddLabels(ctx context.Context, issueID string, labelIDs []string) (*Issue, error) {
	iid := parseID(issueID)
	if _, err := r.requireIssueProjectMember(ctx, iid); err != nil {
		return nil, err
	}
	for _, lid := range labelIDs {
		if err := r.IssueSvc.AddLabel(iid, parseID(lid)); err != nil {
			return nil, fmt.Errorf("add label: %w", err)
		}
	}
	issue, err := r.IssueSvc.GetByID(iid)
	if err != nil {
		return nil, err
	}
	return issueFromModel(issue), nil
}

// RemoveLabels is the resolver for the removeLabels field.
func (r *mutationResolver) RemoveLabels(ctx context.Context, issueID string, labelIDs []string) (*Issue, error) {
	iid := parseID(issueID)
	if _, err := r.requireIssueProjectMember(ctx, iid); err != nil {
		return nil, err
	}
	for _, lid := range labelIDs {
		if err := r.IssueSvc.RemoveLabel(iid, parseID(lid)); err != nil {
			return nil, fmt.Errorf("remove label: %w", err)
		}
	}
	issue, err := r.IssueSvc.GetByID(iid)
	if err != nil {
		return nil, err
	}
	return issueFromModel(issue), nil
}

// CreateLabel is the resolver for the createLabel field.
func (r *mutationResolver) CreateLabel(ctx context.Context, projectID string, name string, color *string, capability *string, group *string) (*Label, error) {
	pid := parseID(projectID)
	if _, err := r.requireProjectOwner(ctx, pid); err != nil {
		return nil, err
	}
	c := ""
	if color != nil {
		c = *color
	}
	cap := ""
	if capability != nil {
		cap = *capability
	}
	g := ""
	if group != nil {
		g = *group
	}
	l, err := r.ProjectSvc.CreateLabel(pid, name, c, cap, g)
	if err != nil {
		return nil, fmt.Errorf("create label: %w", err)
	}
	return labelFromModel(l), nil
}

// UpdateLabel is the resolver for the updateLabel field.
func (r *mutationResolver) UpdateLabel(ctx context.Context, id string, name *string, color *string) (*Label, error) {
	label, err := r.ProjectSvc.GetLabelByID(parseID(id))
	if err != nil {
		return nil, fmt.Errorf("标签不存在")
	}
	if _, err := r.requireProjectOwner(ctx, label.ProjectID); err != nil {
		return nil, err
	}
	n := ""
	if name != nil {
		n = *name
	}
	c := ""
	if color != nil {
		c = *color
	}
	l, err := r.ProjectSvc.UpdateLabel(parseID(id), n, c)
	if err != nil {
		return nil, fmt.Errorf("update label: %w", err)
	}
	return labelFromModel(l), nil
}

// DeleteLabel is the resolver for the deleteLabel field.
func (r *mutationResolver) DeleteLabel(ctx context.Context, id string) (bool, error) {
	label, err := r.ProjectSvc.GetLabelByID(parseID(id))
	if err != nil {
		return false, fmt.Errorf("标签不存在")
	}
	if _, err := r.requireProjectOwner(ctx, label.ProjectID); err != nil {
		return false, err
	}
	if err := r.ProjectSvc.DeleteLabel(parseID(id)); err != nil {
		return false, fmt.Errorf("delete label: %w", err)
	}
	return true, nil
}

// CreateMilestone is the resolver for the createMilestone field.
func (r *mutationResolver) CreateMilestone(ctx context.Context, projectID string, title string, description *string, dueDate *time.Time) (*Milestone, error) {
	pid := parseID(projectID)
	if _, err := r.requireProjectOwner(ctx, pid); err != nil {
		return nil, err
	}
	d := ""
	if description != nil {
		d = *description
	}
	var nt *models.UnixNullTime
	if dueDate != nil {
		nt = &models.UnixNullTime{Time: *dueDate, Valid: true}
	}
	m, err := r.ProjectSvc.CreateMilestone(pid, title, d, nt)
	if err != nil {
		return nil, fmt.Errorf("create milestone: %w", err)
	}
	return milestoneFromModel(m), nil
}

// UpdateMilestone is the resolver for the updateMilestone field.
func (r *mutationResolver) UpdateMilestone(ctx context.Context, id string, title *string, description *string, dueDate *time.Time, state *MilestoneState) (*Milestone, error) {
	milestone, err := r.ProjectSvc.GetMilestoneByID(parseID(id))
	if err != nil {
		return nil, fmt.Errorf("里程碑不存在")
	}
	if _, err := r.requireProjectOwner(ctx, milestone.ProjectID); err != nil {
		return nil, err
	}
	t := ""
	if title != nil {
		t = *title
	}
	d := ""
	if description != nil {
		d = *description
	}
	var nt *models.UnixNullTime
	if dueDate != nil {
		nt = &models.UnixNullTime{Time: *dueDate, Valid: true}
	}
	s := models.MilestoneState("")
	if state != nil {
		s = models.MilestoneState(*state)
	}
	m, err := r.ProjectSvc.UpdateMilestone(parseID(id), t, d, nt, s)
	if err != nil {
		return nil, fmt.Errorf("update milestone: %w", err)
	}
	return milestoneFromModel(m), nil
}

// DeleteMilestone is the resolver for the deleteMilestone field.
func (r *mutationResolver) DeleteMilestone(ctx context.Context, id string) (bool, error) {
	milestone, err := r.ProjectSvc.GetMilestoneByID(parseID(id))
	if err != nil {
		return false, fmt.Errorf("里程碑不存在")
	}
	if _, err := r.requireProjectOwner(ctx, milestone.ProjectID); err != nil {
		return false, err
	}
	if err := r.ProjectSvc.DeleteMilestone(parseID(id)); err != nil {
		return false, fmt.Errorf("delete milestone: %w", err)
	}
	return true, nil
}

// CreateFeedback is the resolver for the createFeedback field.
func (r *mutationResolver) CreateFeedback(ctx context.Context, targetType FeedbackTargetType, targetID string, authorID string, rating FeedbackRating, body *string) (*Feedback, error) {
	agentID, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}
	if parseID(authorID) != agentID {
		return nil, errors.New("authorID 与认证身份不匹配")
	}
	b := ""
	if body != nil {
		b = *body
	}
	f, err := r.FeedbackSvc.Create(models.FeedbackTargetType(targetType), parseID(targetID), agentID, feedbackRatingToInt(rating), b)
	if err != nil {
		return nil, fmt.Errorf("create feedback: %w", err)
	}
	return feedbackFromModel(f), nil
}

// CreateProposal is the resolver for the createProposal field.
func (r *mutationResolver) CreateProposal(ctx context.Context, projectID string, title string, description *string, priority Priority, labelIDs []string) (*Proposal, error) {
	agentID, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}
	pid := parseID(projectID)
	if _, err := r.requireProjectMember(ctx, pid); err != nil {
		return nil, err
	}
	desc := ""
	if description != nil {
		desc = *description
	}
	labelUintIDs := make([]uint, len(labelIDs))
	for i, id := range labelIDs {
		labelUintIDs[i] = parseID(id)
	}
	proposal, err := r.ProposalSvc.Create(pid, agentID, title, desc, models.Priority(priority), labelUintIDs)
	if err != nil {
		return nil, fmt.Errorf("create proposal: %w", err)
	}
	return proposalFromModel(proposal), nil
}

// UpdateProposal is the resolver for the updateProposal field.
func (r *mutationResolver) UpdateProposal(ctx context.Context, id string, title *string, description *string, priority *Priority) (*Proposal, error) {
	if _, err := requireAuth(ctx); err != nil {
		return nil, err
	}
	pid := parseID(id)
	changes := map[string]interface{}{}
	if title != nil {
		changes["title"] = *title
	}
	if description != nil {
		changes["description"] = *description
	}
	if priority != nil {
		changes["priority"] = string(*priority)
	}
	if err := r.ProposalSvc.Update(pid, changes); err != nil {
		return nil, fmt.Errorf("update proposal: %w", err)
	}
	p, err := r.ProposalSvc.GetByID(pid)
	if err != nil {
		return nil, err
	}
	return proposalFromModel(p), nil
}

// TransitionProposal is the resolver for the transitionProposal field.
func (r *mutationResolver) TransitionProposal(ctx context.Context, id string, newState ProposalState, actorID string, note *string) (*Proposal, error) {
	agentID, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}
	if parseID(actorID) != agentID {
		return nil, errors.New("actorID 与认证身份不匹配")
	}
	prop, err := r.ProposalSvc.TransitionState(parseID(id), models.ProposalState(newState), agentID, note)
	if err != nil {
		return nil, fmt.Errorf("transition proposal: %w", err)
	}
	return proposalFromModel(prop), nil
}

// ReviewProposal is the resolver for the reviewProposal field.
func (r *mutationResolver) ReviewProposal(ctx context.Context, id string, reviewerID string, approved bool, note *string) (*Proposal, error) {
	if _, err := requireAuth(ctx); err != nil {
		return nil, err
	}
	prop, err := r.ProposalSvc.Review(parseID(id), parseID(reviewerID), approved, note)
	if err != nil {
		return nil, fmt.Errorf("review proposal: %w", err)
	}
	return proposalFromModel(prop), nil
}

// DeleteProposal is the resolver for the deleteProposal field.
func (r *mutationResolver) DeleteProposal(ctx context.Context, id string) (bool, error) {
	if _, err := requireAuth(ctx); err != nil {
		return false, err
	}
	if err := r.ProposalSvc.Delete(parseID(id)); err != nil {
		return false, fmt.Errorf("delete proposal: %w", err)
	}
	return true, nil
}

// CreateTask is the resolver for the createTask field.
func (r *mutationResolver) CreateTask(ctx context.Context, proposalID string, title string, description *string, priority *Priority, assigneeID *string) (*Task, error) {
	agentID, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}
	pid := parseID(proposalID)
	desc := ""
	if description != nil {
		desc = *description
	}
	prio := models.PriorityMedium
	if priority != nil {
		prio = models.Priority(*priority)
	}
	var aID *uint
	if assigneeID != nil && *assigneeID != "" {
		v := parseID(*assigneeID)
		aID = &v
	}
	proposal, err := r.ProposalSvc.GetByID(pid)
	if err != nil {
		return nil, fmt.Errorf("get proposal: %w", err)
	}
	task, err := r.TaskSvc.Create(pid, proposal.ProjectID, agentID, title, desc, prio, aID)
	if err != nil {
		return nil, fmt.Errorf("create task: %w", err)
	}
	return taskFromModel(task), nil
}

// UpdateTask is the resolver for the updateTask field.
func (r *mutationResolver) UpdateTask(ctx context.Context, id string, title *string, description *string, priority *Priority, state *TaskState) (*Task, error) {
	if _, err := requireAuth(ctx); err != nil {
		return nil, err
	}
	tid := parseID(id)
	changes := map[string]interface{}{}
	if title != nil {
		changes["title"] = *title
	}
	if description != nil {
		changes["description"] = *description
	}
	if priority != nil {
		changes["priority"] = string(*priority)
	}
	if state != nil {
		changes["state"] = string(*state)
	}
	if err := r.TaskSvc.Update(tid, changes); err != nil {
		return nil, fmt.Errorf("update task: %w", err)
	}
	t, err := r.TaskSvc.GetByID(tid)
	if err != nil {
		return nil, err
	}
	return taskFromModel(t), nil
}

// AssignTask is the resolver for the assignTask field.
func (r *mutationResolver) AssignTask(ctx context.Context, id string, assigneeID string) (*Task, error) {
	if _, err := requireAuth(ctx); err != nil {
		return nil, err
	}
	t, err := r.TaskSvc.Assign(parseID(id), parseID(assigneeID))
	if err != nil {
		return nil, fmt.Errorf("assign task: %w", err)
	}
	return taskFromModel(t), nil
}

// LinkIssuesToTask is the resolver for the linkIssuesToTask field.
func (r *mutationResolver) LinkIssuesToTask(ctx context.Context, taskID string, issueIDs []string) (*Task, error) {
	if _, err := requireAuth(ctx); err != nil {
		return nil, err
	}
	tid := parseID(taskID)
	for _, iid := range issueIDs {
		if err := r.TaskSvc.LinkIssue(tid, parseID(iid)); err != nil {
			return nil, fmt.Errorf("link issue: %w", err)
		}
	}
	t, err := r.TaskSvc.GetByID(tid)
	if err != nil {
		return nil, err
	}
	return taskFromModel(t), nil
}

// UnlinkIssueFromTask is the resolver for the unlinkIssueFromTask field.
func (r *mutationResolver) UnlinkIssueFromTask(ctx context.Context, taskID string, issueID string) (*Task, error) {
	if _, err := requireAuth(ctx); err != nil {
		return nil, err
	}
	if err := r.TaskSvc.UnlinkIssue(parseID(taskID), parseID(issueID)); err != nil {
		return nil, fmt.Errorf("unlink issue: %w", err)
	}
	t, err := r.TaskSvc.GetByID(parseID(taskID))
	if err != nil {
		return nil, err
	}
	return taskFromModel(t), nil
}

// DeleteTask is the resolver for the deleteTask field.
func (r *mutationResolver) DeleteTask(ctx context.Context, id string) (bool, error) {
	if _, err := requireAuth(ctx); err != nil {
		return false, err
	}
	if err := r.TaskSvc.Delete(parseID(id)); err != nil {
		return false, fmt.Errorf("delete task: %w", err)
	}
	return true, nil
}

// SupportedModels is the resolver for the supportedModels field.
func (r *queryResolver) SupportedModels(ctx context.Context) ([]string, error) {
	return models.SupportedModels, nil
}

// CommonDeviceInfo is the resolver for the commonDeviceInfo field.
func (r *queryResolver) CommonDeviceInfo(ctx context.Context) ([]string, error) {
	return models.CommonDeviceInfo, nil
}

// AllowHumanRegistration is the resolver for the allowHumanRegistration field.
func (r *queryResolver) AllowHumanRegistration(ctx context.Context) (bool, error) {
	return r.HumanReg, nil
}

// Agents is the resolver for the agents field.
func (r *queryResolver) Agents(ctx context.Context, kind *AgentKind, status *AgentStatus, capabilities []string, projectID *string) ([]*Agent, error) {
	if _, err := requireAuth(ctx); err != nil {
		return nil, err
	}
	filter := models.AgentFilter{}
	if kind != nil {
		k := models.AgentKind(*kind)
		filter.Kind = &k
	}
	if status != nil {
		s := models.AgentStatus(*status)
		filter.Status = &s
	}
	if projectID != nil {
		pid := parseID(*projectID)
		filter.ProjectID = &pid
	}
	if len(capabilities) > 0 {
		caps := make([]models.CapabilityType, len(capabilities))
		for i, c := range capabilities {
			caps[i] = models.CapabilityType(c)
		}
		filter.Capabilities = caps
	}
	agents, err := r.AgentSvc.List(filter)
	if err != nil {
		return nil, fmt.Errorf("list agents: %w", err)
	}
	result := make([]*Agent, len(agents))
	for i, a := range agents {
		result[i] = agentFromModel(&a)
	}
	return result, nil
}

// Agent is the resolver for the agent field.
func (r *queryResolver) Agent(ctx context.Context, id string) (*Agent, error) {
	if _, err := r.requireAgentAccess(ctx, parseID(id)); err != nil {
		return nil, err
	}
	a, err := r.AgentSvc.GetByID(parseID(id))
	if err != nil {
		return nil, fmt.Errorf("get agent: %w", err)
	}
	return agentFromModel(a), nil
}

// Projects is the resolver for the projects field.
func (r *queryResolver) Projects(ctx context.Context) ([]*Project, error) {
	agentID, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}
	projects, err := r.ProjectSvc.ListByAgent(agentID)
	if err != nil {
		return nil, fmt.Errorf("list projects: %w", err)
	}
	result := make([]*Project, len(projects))
	for i, p := range projects {
		result[i] = projectFromModel(&p)
	}
	return result, nil
}

// Project is the resolver for the project field.
func (r *queryResolver) Project(ctx context.Context, id string) (*Project, error) {
	pid := parseID(id)
	if _, err := r.requireProjectMember(ctx, pid); err != nil {
		return nil, err
	}
	p, err := r.ProjectSvc.GetByID(pid)
	if err != nil {
		return nil, fmt.Errorf("get project: %w", err)
	}
	return projectFromModel(p), nil
}

// Labels is the resolver for the labels field.
func (r *queryResolver) Labels(ctx context.Context, projectID string, group *string) ([]*Label, error) {
	pid := parseID(projectID)
	if _, err := r.requireProjectMember(ctx, pid); err != nil {
		return nil, err
	}
	g := ""
	if group != nil {
		g = *group
	}
	labels, err := r.ProjectSvc.ListLabels(pid, g)
	if err != nil {
		return nil, fmt.Errorf("list labels: %w", err)
	}
	result := make([]*Label, len(labels))
	for i, l := range labels {
		result[i] = labelFromModel(&l)
	}
	return result, nil
}

// Milestones is the resolver for the milestones field.
func (r *queryResolver) Milestones(ctx context.Context, projectID string, state *MilestoneState) ([]*Milestone, error) {
	pid := parseID(projectID)
	if _, err := r.requireProjectMember(ctx, pid); err != nil {
		return nil, err
	}
	s := models.MilestoneState("")
	if state != nil {
		s = models.MilestoneState(*state)
	}
	milestones, err := r.ProjectSvc.ListMilestones(pid, s)
	if err != nil {
		return nil, fmt.Errorf("list milestones: %w", err)
	}
	result := make([]*Milestone, len(milestones))
	for i, m := range milestones {
		result[i] = milestoneFromModel(&m)
	}
	return result, nil
}

// Issue is the resolver for the issue field.
func (r *queryResolver) Issue(ctx context.Context, id string) (*Issue, error) {
	iid := parseID(id)
	if _, err := r.requireIssueProjectMember(ctx, iid); err != nil {
		return nil, err
	}
	issue, err := r.IssueSvc.GetByID(iid)
	if err != nil {
		return nil, fmt.Errorf("get issue: %w", err)
	}
	return issueFromModel(issue), nil
}

// Issues is the resolver for the issues field.
func (r *queryResolver) Issues(ctx context.Context, projectID string, state *IssueState, priority *Priority, assigneeID *string, labelIDs []string, search *string, limit *int32, offset *int32) (*IssueConnection, error) {
	pid := parseID(projectID)
	if _, err := r.requireProjectMember(ctx, pid); err != nil {
		return nil, err
	}
	filter := models.IssueFilter{ProjectID: uintPtr(pid)}
	if state != nil {
		filter.State = []models.IssueState{models.IssueState(*state)}
	}
	if priority != nil {
		p := models.Priority(*priority)
		filter.Priority = &p
	}
	if assigneeID != nil {
		filter.AssigneeIDs = []uint{parseID(*assigneeID)}
	}
	if len(labelIDs) > 0 {
		ids := make([]uint, len(labelIDs))
		for i, lid := range labelIDs {
			ids[i] = parseID(lid)
		}
		filter.LabelIDs = ids
	}
	if search != nil {
		filter.Search = *search
	}
	if limit != nil {
		filter.Limit = int(*limit)
	}
	if offset != nil {
		filter.Offset = int(*offset)
	}

	issues, total, err := r.IssueSvc.List(filter)
	if err != nil {
		return nil, fmt.Errorf("list issues: %w", err)
	}
	result := make([]*Issue, len(issues))
	for i, iss := range issues {
		result[i] = issueFromModel(&iss)
	}
	return &IssueConnection{
		Edges: result,
		Total: int32(total),
	}, nil
}

// Proposal is the resolver for the proposal field.
func (r *queryResolver) Proposal(ctx context.Context, id string) (*Proposal, error) {
	if _, err := requireAuth(ctx); err != nil {
		return nil, err
	}
	p, err := r.ProposalSvc.GetByID(parseID(id))
	if err != nil {
		return nil, fmt.Errorf("get proposal: %w", err)
	}
	return proposalFromModel(p), nil
}

// Proposals is the resolver for the proposals field.
func (r *queryResolver) Proposals(ctx context.Context, projectID string, state *ProposalState, priority *Priority, search *string, limit *int32, offset *int32) (*ProposalConnection, error) {
	pid := parseID(projectID)
	if _, err := r.requireProjectMember(ctx, pid); err != nil {
		return nil, err
	}
	filter := models.ProposalFilter{ProjectID: uintPtr(pid)}
	if state != nil {
		filter.State = []models.ProposalState{models.ProposalState(*state)}
	}
	if priority != nil {
		p := models.Priority(*priority)
		filter.Priority = &p
	}
	if search != nil {
		filter.Search = *search
	}
	if limit != nil {
		filter.Limit = int(*limit)
	}
	if offset != nil {
		filter.Offset = int(*offset)
	}
	proposals, total, err := r.ProposalSvc.List(filter)
	if err != nil {
		return nil, fmt.Errorf("list proposals: %w", err)
	}
	result := make([]*Proposal, len(proposals))
	for i, p := range proposals {
		result[i] = proposalFromModel(&p)
	}
	return &ProposalConnection{Edges: result, Total: int32(total)}, nil
}

// ValidProposalTransitions is the resolver for the validProposalTransitions field.
func (r *queryResolver) ValidProposalTransitions(ctx context.Context, state ProposalState) ([]ProposalState, error) {
	states, err := r.ProposalSvc.ValidTransitions(models.ProposalState(state))
	if err != nil {
		return nil, fmt.Errorf("valid proposal transitions: %w", err)
	}
	result := make([]ProposalState, len(states))
	for i, s := range states {
		result[i] = ProposalState(s)
	}
	return result, nil
}

// Task is the resolver for the task field.
func (r *queryResolver) Task(ctx context.Context, id string) (*Task, error) {
	if _, err := requireAuth(ctx); err != nil {
		return nil, err
	}
	t, err := r.TaskSvc.GetByID(parseID(id))
	if err != nil {
		return nil, fmt.Errorf("get task: %w", err)
	}
	return taskFromModel(t), nil
}

// Tasks is the resolver for the tasks field.
func (r *queryResolver) Tasks(ctx context.Context, proposalID string, state *TaskState, assigneeID *string, search *string, limit *int32, offset *int32) (*TaskConnection, error) {
	pid := parseID(proposalID)
	if _, err := requireAuth(ctx); err != nil {
		return nil, err
	}
	filter := models.TaskFilter{ProposalID: uintPtr(pid)}
	if state != nil {
		filter.State = []models.TaskState{models.TaskState(*state)}
	}
	if assigneeID != nil && *assigneeID != "" {
		v := parseID(*assigneeID)
		filter.AssigneeID = &v
	}
	if search != nil {
		filter.Search = *search
	}
	if limit != nil {
		filter.Limit = int(*limit)
	}
	if offset != nil {
		filter.Offset = int(*offset)
	}
	tasks, total, err := r.TaskSvc.List(filter)
	if err != nil {
		return nil, fmt.Errorf("list tasks: %w", err)
	}
	result := make([]*Task, len(tasks))
	for i, t := range tasks {
		result[i] = taskFromModel(&t)
	}
	return &TaskConnection{Edges: result, Total: int32(total)}, nil
}

// ValidTaskTransitions is the resolver for the validTaskTransitions field.
func (r *queryResolver) ValidTaskTransitions(ctx context.Context, state TaskState) ([]TaskState, error) {
	states, err := r.TaskSvc.ValidTransitions(models.TaskState(state))
	if err != nil {
		return nil, fmt.Errorf("valid task transitions: %w", err)
	}
	result := make([]TaskState, len(states))
	for i, s := range states {
		result[i] = TaskState(s)
	}
	return result, nil
}

// Comments is the resolver for the comments field.
func (r *queryResolver) Comments(ctx context.Context, issueID *string, proposalID *string, taskID *string) ([]*Comment, error) {
	switch {
	case issueID != nil:
		iid := parseID(*issueID)
		if _, err := r.requireIssueProjectMember(ctx, iid); err != nil {
			return nil, err
		}
		comments, err := r.CommentSvc.ListByIssue(iid)
		if err != nil {
			return nil, fmt.Errorf("list comments: %w", err)
		}
		result := make([]*Comment, len(comments))
		for i, c := range comments {
			result[i] = commentFromModel(&c)
		}
		return result, nil
	case proposalID != nil:
		pid := parseID(*proposalID)
		comments, err := r.CommentSvc.ListByProposal(pid)
		if err != nil {
			return nil, fmt.Errorf("list comments: %w", err)
		}
		result := make([]*Comment, len(comments))
		for i, c := range comments {
			result[i] = commentFromModel(&c)
		}
		return result, nil
	case taskID != nil:
		tid := parseID(*taskID)
		comments, err := r.CommentSvc.ListByTask(tid)
		if err != nil {
			return nil, fmt.Errorf("list comments: %w", err)
		}
		result := make([]*Comment, len(comments))
		for i, c := range comments {
			result[i] = commentFromModel(&c)
		}
		return result, nil
	default:
		return nil, errors.New("one of issueID, proposalID, or taskID is required")
	}
}

// Timeline is the resolver for the timeline field.
func (r *queryResolver) Timeline(ctx context.Context, issueID *string, proposalID *string, taskID *string) ([]*TimelineEvent, error) {
	switch {
	case issueID != nil:
		iid := parseID(*issueID)
		if _, err := r.requireIssueProjectMember(ctx, iid); err != nil {
			return nil, err
		}
		events, err := r.IssueSvc.ListTimeline(iid)
		if err != nil {
			return nil, fmt.Errorf("list timeline: %w", err)
		}
		result := make([]*TimelineEvent, len(events))
		for i, e := range events {
			result[i] = timelineFromModel(&e)
		}
		return result, nil
	case proposalID != nil:
		pid := parseID(*proposalID)
		events, err := r.ProposalSvc.ListTimeline(pid)
		if err != nil {
			return nil, fmt.Errorf("list timeline: %w", err)
		}
		result := make([]*TimelineEvent, len(events))
		for i, e := range events {
			result[i] = timelineFromModel(&e)
		}
		return result, nil
	case taskID != nil:
		tid := parseID(*taskID)
		events, err := r.TaskSvc.ListTimeline(tid)
		if err != nil {
			return nil, fmt.Errorf("list timeline: %w", err)
		}
		result := make([]*TimelineEvent, len(events))
		for i, e := range events {
			result[i] = timelineFromModel(&e)
		}
		return result, nil
	default:
		return nil, errors.New("one of issueID, proposalID, or taskID is required")
	}
}

// ValidTransitions is the resolver for the validTransitions field.
func (r *queryResolver) ValidTransitions(ctx context.Context, state IssueState) ([]IssueState, error) {
	states, err := r.WorkflowSvc.ValidTransitions(models.IssueState(state))
	if err != nil {
		return nil, fmt.Errorf("valid transitions: %w", err)
	}
	result := make([]IssueState, len(states))
	for i, s := range states {
		result[i] = IssueState(s)
	}
	return result, nil
}

// Feedback is the resolver for the feedback field.
func (r *queryResolver) Feedback(ctx context.Context, targetType FeedbackTargetType, targetID string) ([]*Feedback, error) {
	agentID, err := requireAuth(ctx)
	if err != nil {
		return nil, err
	}
	tid := parseID(targetID)
	switch targetType {
	case FeedbackTargetTypeIssue:
		if _, err := r.requireIssueProjectMember(ctx, tid); err != nil {
			return nil, err
		}
	case FeedbackTargetTypeAgent:
		if _, err := r.requireAgentAccess(ctx, tid); err != nil {
			return nil, err
		}
	case FeedbackTargetTypeAssignment:
		// Only the assigned agent can view assignment feedback
		if agentID != tid {
			return nil, errors.New("无权访问该 feedback")
		}
	case FeedbackTargetTypeComment:
		comment, err := r.CommentSvc.GetByID(tid)
		if err != nil {
			return nil, fmt.Errorf("comment not found")
		}
		if comment.IssueID != nil {
			if _, err := r.requireIssueProjectMember(ctx, parseID(formatID(*comment.IssueID))); err != nil {
				return nil, err
			}
		}
		list, err := r.FeedbackSvc.ListByTarget(models.FeedbackTargetType(targetType), tid)
		if err != nil {
			return nil, fmt.Errorf("list feedback: %w", err)
		}
		result := make([]*Feedback, len(list))
		for i, f := range list {
			result[i] = feedbackFromModel(&f)
		}
		return result, nil
	}
	return nil, errors.New("unknown target type")
}

// IssueUpdated is the resolver for the issueUpdated field.
func (r *subscriptionResolver) IssueUpdated(ctx context.Context, issueID string) (<-chan *Issue, error) {
	id := parseID(issueID)
	// Verify caller has access to this issue's project
	if _, err := r.requireIssueProjectMember(ctx, id); err != nil {
		return nil, err
	}

	ch := make(chan *Issue, 1)

	// Publish initial state
	issue, err := r.IssueSvc.GetByID(id)
	if err == nil {
		ch <- issueFromModel(issue)
	}

	cancel := func() {}
	if r.EventBus != nil {
		cancel = r.EventBus.Subscribe(events.EventIssueStateChanged, func(evt events.Event) {
			payload, ok := evt.Payload.(events.IssueStateChangedPayload)
			if !ok {
				return
			}
			if payload.IssueID == id {
				issue, err := r.IssueSvc.GetByID(id)
				if err == nil {
					select {
					case ch <- issueFromModel(issue):
					default:
					}
				}
			}
		})
	}

	go func() {
		<-ctx.Done()
		cancel()
		close(ch)
	}()

	return ch, nil
}

// AgentNotifications is the resolver for the agentNotifications field.
func (r *subscriptionResolver) AgentNotifications(ctx context.Context, agentID string) (<-chan *NotificationEvent, error) {
	id := parseID(agentID)
	// Verify the caller is requesting their own notifications
	if _, err := requireSelfAccess(ctx, id); err != nil {
		return nil, err
	}

	ch := make(chan *NotificationEvent, 5)

	cancel1 := func() {}
	cancel2 := func() {}
	if r.EventBus != nil {
		cancel1 = r.EventBus.Subscribe(events.EventIssueAssigneeChanged, func(evt events.Event) {
			payload, ok := evt.Payload.(events.IssueAssigneeChangedPayload)
			if !ok {
				return
			}
			if payload.AgentID == id {
				msg := "You have been assigned to an issue"
				if payload.Action == "removed" {
					msg = "You have been unassigned from an issue"
				}
				select {
				case ch <- &NotificationEvent{
					ID:               fmt.Sprintf("notif-%d", time.Now().UnixNano()),
					NotificationType: "assignee_changed",
					Message:          msg,
					Read:             false,
					CreatedAt:        time.Now(),
				}:
				default:
				}
			}
		})

		cancel2 = r.EventBus.Subscribe(events.EventCommentAdded, func(evt events.Event) {
			_, ok := evt.Payload.(events.CommentAddedPayload)
			if !ok {
				return
			}
			select {
			case ch <- &NotificationEvent{
				ID:               fmt.Sprintf("notif-%d", time.Now().UnixNano()),
				NotificationType: "comment_added",
				Message:          "New comment on an issue",
				Read:             false,
				CreatedAt:        time.Now(),
			}:
			default:
			}
		})
	}

	go func() {
		<-ctx.Done()
		cancel1()
		cancel2()
		close(ch)
	}()

	return ch, nil
}

// AgentStatusChanged is the resolver for the agentStatusChanged field.
func (r *subscriptionResolver) AgentStatusChanged(ctx context.Context) (<-chan *AgentStatusEvent, error) {
	ch := make(chan *AgentStatusEvent, 5)

	cancel := func() {}
	if r.EventBus != nil {
		cancel = r.EventBus.Subscribe(events.EventAgentStatusChanged, func(evt events.Event) {
			payload, ok := evt.Payload.(events.AgentStatusChangedPayload)
			if !ok {
				return
			}
			select {
			case ch <- &AgentStatusEvent{
				AgentID:   formatID(payload.AgentID),
				Status:    AgentStatus(models.AgentStatus(payload.Status)),
				Timestamp: time.Now(),
			}:
			default:
			}
		})
	}

	go func() {
		<-ctx.Done()
		cancel()
		close(ch)
	}()

	return ch, nil
}

// Mutation returns MutationResolver implementation.
func (r *Resolver) Mutation() MutationResolver { return &mutationResolver{r} }

// Query returns QueryResolver implementation.
func (r *Resolver) Query() QueryResolver { return &queryResolver{r} }

// Subscription returns SubscriptionResolver implementation.
func (r *Resolver) Subscription() SubscriptionResolver { return &subscriptionResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
type subscriptionResolver struct{ *Resolver }
