package config

import (
	"os"
	"path/filepath"
	"testing"
)

func writeConfig(t *testing.T, dir, content string) {
	t.Helper()
	os.MkdirAll(dir, 0755)
	os.WriteFile(filepath.Join(dir, "config.yaml"), []byte(content), 0644)
}

func TestDefaults(t *testing.T) {
	cfg, err := Load("")
	if err != nil {
		t.Fatalf("Load() error: %v", err)
	}
	if cfg.LLM.Type != "openai" {
		t.Errorf("default llm.type = %q, want openai", cfg.LLM.Type)
	}
	if cfg.LLM.MaxTokens != 4096 {
		t.Errorf("default llm.max_tokens = %d, want 4096", cfg.LLM.MaxTokens)
	}
	if cfg.Session.MaxLoop != 50 {
		t.Errorf("default session.max_loop = %d, want 50", cfg.Session.MaxLoop)
	}
	if !cfg.Transport.Stdio.Enabled {
		t.Error("default transport.stdio.enabled = false, want true")
	}
	if !cfg.MCP.Shell.Enabled {
		t.Error("default mcp.shell.enabled = false, want true")
	}
}

func TestLoadConfigFile(t *testing.T) {
	dir := t.TempDir()
	writeConfig(t, dir, `
llm:
  type: "anthropic"
  base_url: "https://api.example.com"
  model: "test-model"
  max_tokens: 2048
session:
  max_loop: 10
transport:
  stdio:
    enabled: false
`)
	orig := ProjectConfigDir
	ProjectConfigDir = dir
	t.Cleanup(func() { ProjectConfigDir = orig })

	cfg, err := Load("")
	if err != nil {
		t.Fatalf("Load() error: %v", err)
	}
	if cfg.LLM.Type != "anthropic" {
		t.Errorf("llm.type = %q, want anthropic", cfg.LLM.Type)
	}
	if cfg.LLM.BaseURL != "https://api.example.com" {
		t.Errorf("llm.base_url = %q", cfg.LLM.BaseURL)
	}
	if cfg.LLM.Model != "test-model" {
		t.Errorf("llm.model = %q", cfg.LLM.Model)
	}
	if cfg.LLM.MaxTokens != 2048 {
		t.Errorf("llm.max_tokens = %d, want 2048", cfg.LLM.MaxTokens)
	}
	if cfg.Session.MaxLoop != 10 {
		t.Errorf("session.max_loop = %d, want 10", cfg.Session.MaxLoop)
	}
	if cfg.Transport.Stdio.Enabled {
		t.Error("transport.stdio.enabled = true, want false")
	}
}

func TestEnvOverrides(t *testing.T) {
	dir := t.TempDir()
	writeConfig(t, dir, `
llm:
  type: "anthropic"
  base_url: "https://config.url"
  model: "config-model"
  max_tokens: 1000
`)
	orig := ProjectConfigDir
	ProjectConfigDir = dir
	t.Cleanup(func() { ProjectConfigDir = orig })

	// Set env vars
	os.Setenv("DZ_LLM_TYPE", "openai")
	os.Setenv("DZ_LLM_BASE_URL", "https://env.url")
	os.Setenv("DZ_LLM_MODEL", "env-model")
	os.Setenv("DZ_LLM_API_KEY", "env-key-123")
	os.Setenv("DZ_LLM_MAX_TOKENS", "500")
	t.Cleanup(func() {
		os.Unsetenv("DZ_LLM_TYPE")
		os.Unsetenv("DZ_LLM_BASE_URL")
		os.Unsetenv("DZ_LLM_MODEL")
		os.Unsetenv("DZ_LLM_API_KEY")
		os.Unsetenv("DZ_LLM_MAX_TOKENS")
	})

	cfg, err := Load("")
	if err != nil {
		t.Fatalf("Load() error: %v", err)
	}
	if cfg.LLM.Type != "openai" {
		t.Errorf("llm.type = %q, want openai", cfg.LLM.Type)
	}
	if cfg.LLM.BaseURL != "https://env.url" {
		t.Errorf("llm.base_url = %q, want https://env.url", cfg.LLM.BaseURL)
	}
	if cfg.LLM.Model != "env-model" {
		t.Errorf("llm.model = %q, want env-model", cfg.LLM.Model)
	}
	if cfg.LLM.APIKey != "env-key-123" {
		t.Errorf("llm.api_key = %q, want env-key-123", cfg.LLM.APIKey)
	}
	if cfg.LLM.MaxTokens != 500 {
		t.Errorf("llm.max_tokens = %d, want 500", cfg.LLM.MaxTokens)
	}
}

func TestEnvOverrideEmptyDoesNotOverride(t *testing.T) {
	dir := t.TempDir()
	writeConfig(t, dir, `
llm:
  type: "anthropic"
  base_url: "https://config.url"
  model: "config-model"
`)
	orig := ProjectConfigDir
	ProjectConfigDir = dir
	t.Cleanup(func() { ProjectConfigDir = orig })

	// Set only the API key env, leave others unset
	os.Setenv("DZ_LLM_API_KEY", "test-key")
	t.Cleanup(func() { os.Unsetenv("DZ_LLM_API_KEY") })

	cfg, err := Load("")
	if err != nil {
		t.Fatalf("Load() error: %v", err)
	}
	if cfg.LLM.Type != "anthropic" {
		t.Errorf("llm.type = %q, want anthropic (should not be overridden)", cfg.LLM.Type)
	}
	if cfg.LLM.BaseURL != "https://config.url" {
		t.Errorf("llm.base_url = %q, want https://config.url", cfg.LLM.BaseURL)
	}
	if cfg.LLM.APIKey != "test-key" {
		t.Errorf("llm.api_key = %q, want test-key", cfg.LLM.APIKey)
	}
}

func TestSessionDirDefault(t *testing.T) {
	cfg, err := Load("")
	if err != nil {
		t.Fatalf("Load() error: %v", err)
	}
	if cfg.Session.Dir == "" {
		t.Error("session.dir should have a default")
	}
}

func TestSSHDefaults(t *testing.T) {
	cfg, err := Load("")
	if err != nil {
		t.Fatalf("Load() error: %v", err)
	}
	if cfg.Transport.SSH.Username != "dolphinzZ" {
		t.Errorf("ssh.username = %q, want dolphinzZ", cfg.Transport.SSH.Username)
	}
	if cfg.Transport.SSH.Addr != ":2222" {
		t.Errorf("ssh.addr = %q, want :2222", cfg.Transport.SSH.Addr)
	}
}

func TestSSHPasswordNotAutoGeneratedWhenDisabled(t *testing.T) {
	dir := t.TempDir()
	writeConfig(t, dir, `
transport:
  ssh:
    enabled: false
`)
	orig := ProjectConfigDir
	ProjectConfigDir = dir
	t.Cleanup(func() { ProjectConfigDir = orig })

	cfg, err := Load("")
	if err != nil {
		t.Fatalf("Load() error: %v", err)
	}
	// Password should still be empty because SSH is disabled
	if cfg.Transport.SSH.Password != "" {
		t.Log("password was auto-generated despite SSH being disabled")
	}
}

func TestSSHPasswordAutoGeneratedWhenEnabled(t *testing.T) {
	dir := t.TempDir()
	writeConfig(t, dir, `
transport:
  ssh:
    enabled: true
`)
	orig := ProjectConfigDir
	ProjectConfigDir = dir
	t.Cleanup(func() { ProjectConfigDir = orig })

	cfg, err := Load("")
	if err != nil {
		t.Fatalf("Load() error: %v", err)
	}
	if cfg.Transport.SSH.Password == "" {
		t.Fatal("expected auto-generated password for enabled SSH")
	}
	if len(cfg.Transport.SSH.Password) < 8 {
		t.Errorf("password too short: %q (len=%d)", cfg.Transport.SSH.Password, len(cfg.Transport.SSH.Password))
	}
}

func TestSSHPasswordPersistsAcrossLoads(t *testing.T) {
	dir := t.TempDir()
	writeConfig(t, dir, `
transport:
  ssh:
    enabled: true
`)
	orig := ProjectConfigDir
	ProjectConfigDir = dir
	t.Cleanup(func() { ProjectConfigDir = orig })

	cfg1, err := Load("")
	if err != nil {
		t.Fatalf("first Load() error: %v", err)
	}
	if cfg1.Transport.SSH.Password == "" {
		t.Fatal("first load: expected auto-generated password")
	}

	// Load again — should reuse persisted password
	cfg2, err := Load("")
	if err != nil {
		t.Fatalf("second Load() error: %v", err)
	}
	if cfg2.Transport.SSH.Password != cfg1.Transport.SSH.Password {
		t.Errorf("password changed between loads: %q -> %q", cfg1.Transport.SSH.Password, cfg2.Transport.SSH.Password)
	}
}

func TestSSHPasswordFromConfig(t *testing.T) {
	dir := t.TempDir()
	writeConfig(t, dir, `
transport:
  ssh:
    enabled: true
    password: "mypassword"
`)
	orig := ProjectConfigDir
	ProjectConfigDir = dir
	t.Cleanup(func() { ProjectConfigDir = orig })

	cfg, err := Load("")
	if err != nil {
		t.Fatalf("Load() error: %v", err)
	}
	if cfg.Transport.SSH.Password != "mypassword" {
		t.Errorf("password = %q, want mypassword", cfg.Transport.SSH.Password)
	}
}

func TestMaxContextTokensDefault(t *testing.T) {
	cfg, err := Load("")
	if err != nil {
		t.Fatalf("Load() error: %v", err)
	}
	if cfg.LLM.MaxContextTokens != 1048576 {
		t.Errorf("max_context_tokens = %d, want 1048576", cfg.LLM.MaxContextTokens)
	}
}

func TestMultiLevelMerge(t *testing.T) {
	// Create three config levels
	sysDir := t.TempDir()
	userHome := t.TempDir()
	projectDir := t.TempDir()

	// System config (lowest priority)
	writeConfig(t, sysDir, `
llm:
  type: "anthropic"
  model: "claude-3"
session:
  max_loop: 10
`)

	// User config (medium priority) — override model, add mcp server
	writeConfig(t, filepath.Join(userHome, ".dolphinzZ"), `
llm:
  model: "gpt-4o"
mcp:
  servers:
    server-a:
      type: "stdio"
      command: "node"
      args: ["a.js"]
`)

	// Project config (highest priority among defaults) — override max_loop, add another server
	writeConfig(t, projectDir, `
session:
  max_loop: 99
mcp:
  servers:
    server-b:
      type: "stdio"
      command: "python"
      args: ["b.py"]
`)

	origSystem := SystemConfigDir
	origProject := ProjectConfigDir
	SystemConfigDir = sysDir
	ProjectConfigDir = projectDir
	t.Cleanup(func() {
		SystemConfigDir = origSystem
		ProjectConfigDir = origProject
	})

	origHome := os.Getenv("HOME")
	os.Setenv("HOME", userHome)
	t.Cleanup(func() { os.Setenv("HOME", origHome) })

	cfg, err := Load("")
	if err != nil {
		t.Fatalf("Load() error: %v", err)
	}

	// From system config (not overridden)
	if cfg.LLM.Type != "anthropic" {
		t.Errorf("llm.type = %q, want anthropic", cfg.LLM.Type)
	}

	// From user config (overrides system)
	if cfg.LLM.Model != "gpt-4o" {
		t.Errorf("llm.model = %q, want gpt-4o", cfg.LLM.Model)
	}

	// From project config (overrides system)
	if cfg.Session.MaxLoop != 99 {
		t.Errorf("session.max_loop = %d, want 99", cfg.Session.MaxLoop)
	}

	// Deep-merge: both servers should exist
	if _, ok := cfg.MCP.Servers["server-a"]; !ok {
		t.Errorf("expected server-a in merged config, got servers: %v", cfg.MCP.Servers)
	}
	if _, ok := cfg.MCP.Servers["server-b"]; !ok {
		t.Errorf("expected server-b in merged config, got servers: %v", cfg.MCP.Servers)
	}

	// server-a args from user config should be preserved
	sa := cfg.MCP.Servers["server-a"]
	if sa.Command != "node" {
		t.Errorf("server-a command = %q, want node", sa.Command)
	}
}

func TestMultiLevelMergeWithCFlag(t *testing.T) {
	projectDir := t.TempDir()
	overrideDir := t.TempDir()

	// Project config
	writeConfig(t, projectDir, `
llm:
  model: "gpt-4o"
session:
  max_loop: 50
`)

	// -c override file (highest priority)
	writeConfig(t, overrideDir, `
session:
  max_loop: 999
`)

	origProject := ProjectConfigDir
	ProjectConfigDir = projectDir
	t.Cleanup(func() { ProjectConfigDir = origProject })

	cfgFile := filepath.Join(overrideDir, "config.yaml")
	cfg, err := Load(cfgFile)
	if err != nil {
		t.Fatalf("Load() error: %v", err)
	}

	// From project config (not overridden by -c)
	if cfg.LLM.Model != "gpt-4o" {
		t.Errorf("llm.model = %q, want gpt-4o", cfg.LLM.Model)
	}

	// From -c flag (overrides project)
	if cfg.Session.MaxLoop != 999 {
		t.Errorf("session.max_loop = %d, want 999", cfg.Session.MaxLoop)
	}
}

func TestMCPServersDeepMerge(t *testing.T) {
	userHome := t.TempDir()
	projectDir := t.TempDir()

	// User config: server-a with args
	writeConfig(t, filepath.Join(userHome, ".dolphinzZ"), `
mcp:
  servers:
    server-a:
      type: "stdio"
      command: "node"
      args: ["index.js"]
      url: ""
`)

	// Project config: server-a overrides args, adds server-b
	writeConfig(t, projectDir, `
mcp:
  servers:
    server-a:
      args: ["override.js"]
    server-b:
      type: "stdio"
      command: "python"
      args: ["server.py"]
`)

	origProject := ProjectConfigDir
	ProjectConfigDir = projectDir
	t.Cleanup(func() { ProjectConfigDir = origProject })

	origHome := os.Getenv("HOME")
	os.Setenv("HOME", userHome)
	t.Cleanup(func() { os.Setenv("HOME", origHome) })

	cfg, err := Load("")
	if err != nil {
		t.Fatalf("Load() error: %v", err)
	}

	// Both servers should exist
	sa, ok := cfg.MCP.Servers["server-a"]
	if !ok {
		t.Fatal("expected server-a in merged config")
	}
	// server-a command from user (not overridden)
	if sa.Command != "node" {
		t.Errorf("server-a command = %q, want node", sa.Command)
	}
	// server-a args overridden by project
	if len(sa.Args) != 1 || sa.Args[0] != "override.js" {
		t.Errorf("server-a args = %v, want [override.js]", sa.Args)
	}

	sb, ok := cfg.MCP.Servers["server-b"]
	if !ok {
		t.Fatal("expected server-b in merged config")
	}
	if sb.Command != "python" {
		t.Errorf("server-b command = %q, want python", sb.Command)
	}
}
